CREATE TABLE BE_CARDS.CLOB_ADDRESS_SOURCE (
    ADDRESS_ID NUMBER(19) NOT NULL,
    CUSTOMER_REF VARCHAR2(32) NOT NULL,
    FULL_ADDRESS CLOB NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_CLOB_ADDRESS_SOURCE PRIMARY KEY (ADDRESS_ID)
);
