DROP SCHEMA IF EXISTS clob_mask_test CASCADE;
CREATE SCHEMA clob_mask_test;

CREATE TABLE clob_mask_test."CLOB_ADDRESS_TARGET" (
    "ADDRESS_ID" BIGINT PRIMARY KEY,
    "CUSTOMER_REF" VARCHAR(32) NOT NULL,
    "FULL_ADDRESS" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL
);
