OPTIONS (ERRORS=0)
LOAD DATA
CHARACTERSET AL32UTF8
INFILE 'D:\\forgetdm - Copy\\docs\\testing\\evidence\\operation-500tb-dual-load\\20260804-113953\\dual-engine-sample.tsv'
APPEND INTO TABLE "TEMENOS_TDM"."OP500_LOAD_DL759TK10"
FIELDS TERMINATED BY X'09' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
("ID" INTEGER EXTERNAL,
 "CUSTOMER_REF" CHAR(32767),
 "AMOUNT" INTEGER EXTERNAL)
