package io.forgetdm.ri;

import io.forgetdm.audit.AuditService;
import io.forgetdm.security.AccessContext;
import io.forgetdm.security.AccessControlService;
import io.forgetdm.security.AccessPrincipal;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.List;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

class RiRegistryAuditCoverageTest {

    @Test
    void keyAndRelationshipMutationsWriteStructuredAuditWithoutDescriptions() {
        JdbcTemplate jdbc = jdbc();
        AuditService audit = mock(AuditService.class);
        RiRegistryService service = new RiRegistryService(jdbc, audit);

        asArchitect(() -> {
            service.createKey(new RiRegistryService.KeyRequest("customer-key", "SECRET key description",
                    "PRIVATE", null, 10L, "public", "customers", "customer_id, tenant_id"));
            service.updateKey(1L, new RiRegistryService.KeyRequest("customer-key-v2", "SECRET update note",
                    "PRIVATE", null, 10L, "public", "customers_new", "customer_id, tenant_id"));
            service.deleteKey(1L);

            service.createRelationship(new RiRegistryService.RelationshipRequest("account-customer", "SECRET rel description",
                    "PRIVATE", null, 10L, "public", "accounts", "customer_id,tenant_id",
                    "public", "customers", "customer_id,tenant_id", "IDENTIFYING", 0, 10));
            service.updateRelationship(1L, new RiRegistryService.RelationshipRequest("account-customer-v2", "SECRET rel update",
                    "PRIVATE", null, 10L, "public", "accounts_new", "customer_id,tenant_id",
                    "public", "customers", "customer_id,tenant_id", "OPTIONAL", 0, 12));
            service.deleteRelationship(1L);
            return null;
        });

        ArgumentCaptor<String> action = ArgumentCaptor.forClass(String.class);
        ArgumentCaptor<String> resourceType = ArgumentCaptor.forClass(String.class);
        ArgumentCaptor<String> resourceId = ArgumentCaptor.forClass(String.class);
        ArgumentCaptor<String> metadata = ArgumentCaptor.forClass(String.class);
        verify(audit, times(6)).record(eq("ri-architect"), action.capture(), eq("REFERENTIAL_INTEGRITY"),
                resourceType.capture(), resourceId.capture(), any(), eq("SUCCESS"), any(), metadata.capture());

        assertEquals(List.of("RI_PK_CREATED", "RI_PK_UPDATED", "RI_PK_DELETED",
                "RI_REL_CREATED", "RI_REL_UPDATED", "RI_REL_DELETED"), action.getAllValues());
        assertEquals(List.of("RI_PRIMARY_KEY", "RI_PRIMARY_KEY", "RI_PRIMARY_KEY",
                "RI_RELATIONSHIP", "RI_RELATIONSHIP", "RI_RELATIONSHIP"), resourceType.getAllValues());
        assertEquals(List.of("1", "1", "1", "1", "1", "1"), resourceId.getAllValues());
        String joined = String.join("\n", metadata.getAllValues());
        assertFalse(joined.contains("SECRET"), joined);
        assertEquals(3, metadata.getAllValues().stream().filter(m -> m.contains("\"keyColumnCount\":2")).count());
        assertEquals(3, metadata.getAllValues().stream().filter(m -> m.contains("\"columnPairCount\":2")).count());
        assertEquals(6, metadata.getAllValues().stream().filter(m -> m.contains("\"dataSourceId\":10")).count());
    }

    private static JdbcTemplate jdbc() {
        JdbcTemplate jdbc = new JdbcTemplate(new DriverManagerDataSource(
                "jdbc:h2:mem:ri_audit_" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", ""));
        jdbc.execute("CREATE TABLE forge_groups(id BIGINT PRIMARY KEY,name VARCHAR(120))");
        jdbc.execute("CREATE TABLE forge_user_groups(user_id BIGINT,group_id BIGINT)");
        jdbc.execute("INSERT INTO forge_groups(id,name) VALUES (101,'qa')");
        jdbc.execute("INSERT INTO forge_user_groups(user_id,group_id) VALUES (11,101)");
        jdbc.execute("CREATE TABLE ri_primary_key(" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "name VARCHAR(160),description VARCHAR(500),visibility VARCHAR(16),owner_user_id BIGINT," +
                "owner_username VARCHAR(120),owner_group_id BIGINT,data_source_id BIGINT,schema_name VARCHAR(200)," +
                "table_name VARCHAR(200),key_columns VARCHAR(1000),created_at TIMESTAMP,updated_at TIMESTAMP)");
        jdbc.execute("CREATE TABLE ri_relationship(" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "name VARCHAR(160),description VARCHAR(500),visibility VARCHAR(16),owner_user_id BIGINT," +
                "owner_username VARCHAR(120),owner_group_id BIGINT,data_source_id BIGINT,child_schema VARCHAR(200)," +
                "child_table VARCHAR(200),child_columns VARCHAR(1000),parent_schema VARCHAR(200)," +
                "parent_table VARCHAR(200),parent_columns VARCHAR(1000),relationship_type VARCHAR(30)," +
                "cardinality_min INTEGER,cardinality_max INTEGER,created_at TIMESTAMP,updated_at TIMESTAMP)");
        return jdbc;
    }

    private static <T> T asArchitect(java.util.function.Supplier<T> work) {
        AccessPrincipal principal = new AccessPrincipal(11L, "ri-architect", "RI Architect",
                Set.of("TDM_ARCHITECT"), Set.of("ri.manage"),
                List.of(new AccessControlService.GroupLite(101L, "qa")));
        return AccessContext.callAs(principal, null, work);
    }
}
