CREATE TABLE "BE_CARDS"."PC_CONTACT" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "PARENT_CONTACT_ID" NUMBER(19),
  "PARTY_KEY" VARCHAR2(180) UNIQUE,
  "FIRST_NAME" VARCHAR2(180),
  "LAST_NAME" VARCHAR2(180),
  "DATE_OF_BIRTH" DATE,
  "TAX_IDENTIFIER" VARCHAR2(180),
  CONSTRAINT "PK_PC_1" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_ADDRESS" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "CONTACT_ID" NUMBER(19),
  "ADDRESS_LINE1" VARCHAR2(180),
  "CITY" VARCHAR2(180),
  "STATE_CODE" VARCHAR2(40),
  "POSTAL_CODE" VARCHAR2(40),
  CONSTRAINT "PK_PC_2" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_ACCOUNT" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "PRIMARY_CONTACT_ID" NUMBER(19),
  CONSTRAINT "PK_PC_3" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_ACCOUNT_CONTACT" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "ACCOUNT_ID" NUMBER(19),
  "CONTACT_ID" NUMBER(19),
  "PARTY_KEY" VARCHAR2(180) UNIQUE,
  "FIRST_NAME" VARCHAR2(180),
  "LAST_NAME" VARCHAR2(180),
  "DATE_OF_BIRTH" DATE,
  "TAX_IDENTIFIER" VARCHAR2(180),
  CONSTRAINT "PK_PC_4" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_POLICY" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "ACCOUNT_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PC_5" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PC_DATES_5" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PC_POLICY_PERIOD" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PC_6" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PC_DATES_6" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PC_POLICY_LINE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PC_7" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PC_DATES_7" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PC_PERSONAL_AUTO_LINE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_LINE_ID" NUMBER(19),
  CONSTRAINT "PK_PC_8" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_VEHICLE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "AUTO_LINE_ID" NUMBER(19),
  "VIN" VARCHAR2(180) UNIQUE,
  "VEHICLE_YEAR" NUMBER(10),
  "MAKE_NAME" VARCHAR2(180),
  "MODEL_NAME" VARCHAR2(180),
  CONSTRAINT "PK_PC_9" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_DRIVER" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "AUTO_LINE_ID" NUMBER(19),
  "CONTACT_ID" NUMBER(19),
  "PARTY_KEY" VARCHAR2(180) UNIQUE,
  "FIRST_NAME" VARCHAR2(180),
  "LAST_NAME" VARCHAR2(180),
  "DATE_OF_BIRTH" DATE,
  "TAX_IDENTIFIER" VARCHAR2(180),
  CONSTRAINT "PK_PC_10" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_VEHICLE_DRIVER" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "VEHICLE_ID" NUMBER(19),
  "DRIVER_ID" NUMBER(19),
  "PARTY_KEY" VARCHAR2(180) UNIQUE,
  "FIRST_NAME" VARCHAR2(180),
  "LAST_NAME" VARCHAR2(180),
  "DATE_OF_BIRTH" DATE,
  "TAX_IDENTIFIER" VARCHAR2(180),
  "VIN" VARCHAR2(180) UNIQUE,
  "VEHICLE_YEAR" NUMBER(10),
  "MAKE_NAME" VARCHAR2(180),
  "MODEL_NAME" VARCHAR2(180),
  CONSTRAINT "PK_PC_11" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_COVERAGE_PATTERN" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  CONSTRAINT "PK_PC_12" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_COVERAGE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_LINE_ID" NUMBER(19),
  "PATTERN_ID" NUMBER(19),
  CONSTRAINT "PK_PC_13" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_COVERAGE_TERM" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "COVERAGE_ID" NUMBER(19),
  "FACTOR_PERCENT" NUMBER(5,2),
  CONSTRAINT "PK_PC_14" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PC_PCT_14" CHECK ("FACTOR_PERCENT" IS NULL OR ("FACTOR_PERCENT" >= 0 AND "FACTOR_PERCENT" <= 100))
);

CREATE TABLE "BE_CARDS"."PC_LOCATION" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "ACCOUNT_ID" NUMBER(19),
  "ADDRESS_ID" NUMBER(19),
  "ADDRESS_LINE1" VARCHAR2(180),
  "CITY" VARCHAR2(180),
  "STATE_CODE" VARCHAR2(40),
  "POSTAL_CODE" VARCHAR2(40),
  CONSTRAINT "PK_PC_15" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_BUILDING" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "LOCATION_ID" NUMBER(19),
  "ADDRESS_LINE1" VARCHAR2(180),
  "CITY" VARCHAR2(180),
  "STATE_CODE" VARCHAR2(40),
  "POSTAL_CODE" VARCHAR2(40),
  CONSTRAINT "PK_PC_16" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_HOMEOWNERS_LINE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_LINE_ID" NUMBER(19),
  CONSTRAINT "PK_PC_17" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_DWELLING" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "HOME_LINE_ID" NUMBER(19),
  "BUILDING_ID" NUMBER(19),
  "ADDRESS_LINE1" VARCHAR2(180),
  "CITY" VARCHAR2(180),
  "STATE_CODE" VARCHAR2(40),
  "POSTAL_CODE" VARCHAR2(40),
  CONSTRAINT "PK_PC_18" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_POLICY_CONTACT_ROLE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "CONTACT_ID" NUMBER(19),
  "PARTY_KEY" VARCHAR2(180) UNIQUE,
  "FIRST_NAME" VARCHAR2(180),
  "LAST_NAME" VARCHAR2(180),
  "DATE_OF_BIRTH" DATE,
  "TAX_IDENTIFIER" VARCHAR2(180),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PC_19" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PC_DATES_19" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PC_UNDERWRITING_ISSUE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  CONSTRAINT "PK_PC_20" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_UNDERWRITING_REFERRAL" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "ISSUE_ID" NUMBER(19),
  CONSTRAINT "PK_PC_21" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_QUOTE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PC_22" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PC_DATES_22" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PC_QUOTE_COST" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "QUOTE_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  "AMOUNT" NUMBER(18,2),
  "CURRENCY_CODE" VARCHAR2(40),
  CONSTRAINT "PK_PC_23" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PC_AMT_23" CHECK ("AMOUNT" IS NULL OR "AMOUNT" >= 0),
  CONSTRAINT "CK_PC_DATES_23" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PC_PREMIUM_TRANSACTION" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "AMOUNT" NUMBER(18,2),
  "CURRENCY_CODE" VARCHAR2(40),
  CONSTRAINT "PK_PC_24" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PC_AMT_24" CHECK ("AMOUNT" IS NULL OR "AMOUNT" >= 0)
);

CREATE TABLE "BE_CARDS"."PC_RATE_BOOK" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  CONSTRAINT "PK_PC_25" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_RATE_TABLE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "RATE_BOOK_ID" NUMBER(19),
  CONSTRAINT "PK_PC_26" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_RATE_FACTOR" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "RATE_TABLE_ID" NUMBER(19),
  "FACTOR_PERCENT" NUMBER(5,2),
  CONSTRAINT "PK_PC_27" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PC_PCT_27" CHECK ("FACTOR_PERCENT" IS NULL OR ("FACTOR_PERCENT" >= 0 AND "FACTOR_PERCENT" <= 100))
);

CREATE TABLE "BE_CARDS"."PC_JOB" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "ACCOUNT_ID" NUMBER(19),
  "POLICY_PERIOD_ID" NUMBER(19),
  CONSTRAINT "PK_PC_28" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_SUBMISSION" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "JOB_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PC_29" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PC_DATES_29" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PC_RENEWAL" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "JOB_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PC_30" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PC_DATES_30" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PC_CANCELLATION" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "JOB_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PC_31" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PC_DATES_31" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PC_REINSTATEMENT" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "JOB_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PC_32" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PC_DATES_32" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PC_DOCUMENT" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "FILE_NAME" VARCHAR2(180),
  "MIME_TYPE" VARCHAR2(180),
  "DOCUMENT_BODY" BLOB,
  CONSTRAINT "PK_PC_33" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_NOTE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "AUTHOR_CONTACT_ID" NUMBER(19),
  "DETAIL_TEXT" CLOB,
  "PAYLOAD_JSON" CLOB,
  CONSTRAINT "PK_PC_34" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_ACTIVITY" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  CONSTRAINT "PK_PC_35" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_WORKFLOW" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "JOB_ID" NUMBER(19),
  "DETAIL_TEXT" CLOB,
  "PAYLOAD_JSON" CLOB,
  CONSTRAINT "PK_PC_36" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_WORKFLOW_STEP" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "WORKFLOW_ID" NUMBER(19),
  "DETAIL_TEXT" CLOB,
  "PAYLOAD_JSON" CLOB,
  CONSTRAINT "PK_PC_37" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_QUESTION_SET" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  CONSTRAINT "PK_PC_38" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_QUESTION" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "QUESTION_SET_ID" NUMBER(19),
  CONSTRAINT "PK_PC_39" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_ANSWER" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "QUESTION_ID" NUMBER(19),
  "POLICY_PERIOD_ID" NUMBER(19),
  CONSTRAINT "PK_PC_40" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_PRODUCT" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PC_41" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PC_DATES_41" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PC_PRODUCT_LINE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "PRODUCT_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PC_42" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PC_DATES_42" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PC_FORM_PATTERN" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "PRODUCT_ID" NUMBER(19),
  CONSTRAINT "PK_PC_43" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_POLICY_FORM" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "FORM_PATTERN_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PC_44" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PC_DATES_44" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PC_PRODUCER" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "CONTACT_ID" NUMBER(19),
  "PARTY_KEY" VARCHAR2(180) UNIQUE,
  "FIRST_NAME" VARCHAR2(180),
  "LAST_NAME" VARCHAR2(180),
  "DATE_OF_BIRTH" DATE,
  "TAX_IDENTIFIER" VARCHAR2(180),
  CONSTRAINT "PK_PC_45" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_PRODUCER_CODE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "PRODUCER_ID" NUMBER(19),
  "PARTY_KEY" VARCHAR2(180) UNIQUE,
  "FIRST_NAME" VARCHAR2(180),
  "LAST_NAME" VARCHAR2(180),
  "DATE_OF_BIRTH" DATE,
  "TAX_IDENTIFIER" VARCHAR2(180),
  CONSTRAINT "PK_PC_46" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_TERRITORY" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  CONSTRAINT "PK_PC_47" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_AUDIT" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "DETAIL_TEXT" CLOB,
  "PAYLOAD_JSON" CLOB,
  CONSTRAINT "PK_PC_48" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_MESSAGE_OUTBOX" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "DETAIL_TEXT" CLOB,
  "PAYLOAD_JSON" CLOB,
  CONSTRAINT "PK_PC_49" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PC_CHANGE_EVENT" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "DETAIL_TEXT" CLOB,
  "PAYLOAD_JSON" CLOB,
  CONSTRAINT "PK_PC_50" PRIMARY KEY ("ID")
);

ALTER TABLE "BE_CARDS"."PC_CONTACT" ADD CONSTRAINT "FK_PC_1_1" FOREIGN KEY ("PARENT_CONTACT_ID") REFERENCES "BE_CARDS"."PC_CONTACT" ("ID");

ALTER TABLE "BE_CARDS"."PC_ADDRESS" ADD CONSTRAINT "FK_PC_2_1" FOREIGN KEY ("CONTACT_ID") REFERENCES "BE_CARDS"."PC_CONTACT" ("ID");

ALTER TABLE "BE_CARDS"."PC_ACCOUNT" ADD CONSTRAINT "FK_PC_3_1" FOREIGN KEY ("PRIMARY_CONTACT_ID") REFERENCES "BE_CARDS"."PC_CONTACT" ("ID");

ALTER TABLE "BE_CARDS"."PC_ACCOUNT_CONTACT" ADD CONSTRAINT "FK_PC_4_1" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "BE_CARDS"."PC_ACCOUNT" ("ID");

ALTER TABLE "BE_CARDS"."PC_ACCOUNT_CONTACT" ADD CONSTRAINT "FK_PC_4_2" FOREIGN KEY ("CONTACT_ID") REFERENCES "BE_CARDS"."PC_CONTACT" ("ID");

ALTER TABLE "BE_CARDS"."PC_POLICY" ADD CONSTRAINT "FK_PC_5_1" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "BE_CARDS"."PC_ACCOUNT" ("ID");

ALTER TABLE "BE_CARDS"."PC_POLICY_PERIOD" ADD CONSTRAINT "FK_PC_6_1" FOREIGN KEY ("POLICY_ID") REFERENCES "BE_CARDS"."PC_POLICY" ("ID");

ALTER TABLE "BE_CARDS"."PC_POLICY_LINE" ADD CONSTRAINT "FK_PC_7_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PC_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PC_PERSONAL_AUTO_LINE" ADD CONSTRAINT "FK_PC_8_1" FOREIGN KEY ("POLICY_LINE_ID") REFERENCES "BE_CARDS"."PC_POLICY_LINE" ("ID");

ALTER TABLE "BE_CARDS"."PC_VEHICLE" ADD CONSTRAINT "FK_PC_9_1" FOREIGN KEY ("AUTO_LINE_ID") REFERENCES "BE_CARDS"."PC_PERSONAL_AUTO_LINE" ("ID");

ALTER TABLE "BE_CARDS"."PC_DRIVER" ADD CONSTRAINT "FK_PC_10_1" FOREIGN KEY ("AUTO_LINE_ID") REFERENCES "BE_CARDS"."PC_PERSONAL_AUTO_LINE" ("ID");

ALTER TABLE "BE_CARDS"."PC_DRIVER" ADD CONSTRAINT "FK_PC_10_2" FOREIGN KEY ("CONTACT_ID") REFERENCES "BE_CARDS"."PC_CONTACT" ("ID");

ALTER TABLE "BE_CARDS"."PC_VEHICLE_DRIVER" ADD CONSTRAINT "FK_PC_11_1" FOREIGN KEY ("VEHICLE_ID") REFERENCES "BE_CARDS"."PC_VEHICLE" ("ID");

ALTER TABLE "BE_CARDS"."PC_VEHICLE_DRIVER" ADD CONSTRAINT "FK_PC_11_2" FOREIGN KEY ("DRIVER_ID") REFERENCES "BE_CARDS"."PC_DRIVER" ("ID");

ALTER TABLE "BE_CARDS"."PC_COVERAGE" ADD CONSTRAINT "FK_PC_13_1" FOREIGN KEY ("POLICY_LINE_ID") REFERENCES "BE_CARDS"."PC_POLICY_LINE" ("ID");

ALTER TABLE "BE_CARDS"."PC_COVERAGE" ADD CONSTRAINT "FK_PC_13_2" FOREIGN KEY ("PATTERN_ID") REFERENCES "BE_CARDS"."PC_COVERAGE_PATTERN" ("ID");

ALTER TABLE "BE_CARDS"."PC_COVERAGE_TERM" ADD CONSTRAINT "FK_PC_14_1" FOREIGN KEY ("COVERAGE_ID") REFERENCES "BE_CARDS"."PC_COVERAGE" ("ID");

ALTER TABLE "BE_CARDS"."PC_LOCATION" ADD CONSTRAINT "FK_PC_15_1" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "BE_CARDS"."PC_ACCOUNT" ("ID");

ALTER TABLE "BE_CARDS"."PC_LOCATION" ADD CONSTRAINT "FK_PC_15_2" FOREIGN KEY ("ADDRESS_ID") REFERENCES "BE_CARDS"."PC_ADDRESS" ("ID");

ALTER TABLE "BE_CARDS"."PC_BUILDING" ADD CONSTRAINT "FK_PC_16_1" FOREIGN KEY ("LOCATION_ID") REFERENCES "BE_CARDS"."PC_LOCATION" ("ID");

ALTER TABLE "BE_CARDS"."PC_HOMEOWNERS_LINE" ADD CONSTRAINT "FK_PC_17_1" FOREIGN KEY ("POLICY_LINE_ID") REFERENCES "BE_CARDS"."PC_POLICY_LINE" ("ID");

ALTER TABLE "BE_CARDS"."PC_DWELLING" ADD CONSTRAINT "FK_PC_18_1" FOREIGN KEY ("HOME_LINE_ID") REFERENCES "BE_CARDS"."PC_HOMEOWNERS_LINE" ("ID");

ALTER TABLE "BE_CARDS"."PC_DWELLING" ADD CONSTRAINT "FK_PC_18_2" FOREIGN KEY ("BUILDING_ID") REFERENCES "BE_CARDS"."PC_BUILDING" ("ID");

ALTER TABLE "BE_CARDS"."PC_POLICY_CONTACT_ROLE" ADD CONSTRAINT "FK_PC_19_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PC_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PC_POLICY_CONTACT_ROLE" ADD CONSTRAINT "FK_PC_19_2" FOREIGN KEY ("CONTACT_ID") REFERENCES "BE_CARDS"."PC_CONTACT" ("ID");

ALTER TABLE "BE_CARDS"."PC_UNDERWRITING_ISSUE" ADD CONSTRAINT "FK_PC_20_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PC_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PC_UNDERWRITING_REFERRAL" ADD CONSTRAINT "FK_PC_21_1" FOREIGN KEY ("ISSUE_ID") REFERENCES "BE_CARDS"."PC_UNDERWRITING_ISSUE" ("ID");

ALTER TABLE "BE_CARDS"."PC_QUOTE" ADD CONSTRAINT "FK_PC_22_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PC_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PC_QUOTE_COST" ADD CONSTRAINT "FK_PC_23_1" FOREIGN KEY ("QUOTE_ID") REFERENCES "BE_CARDS"."PC_QUOTE" ("ID");

ALTER TABLE "BE_CARDS"."PC_PREMIUM_TRANSACTION" ADD CONSTRAINT "FK_PC_24_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PC_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PC_RATE_TABLE" ADD CONSTRAINT "FK_PC_26_1" FOREIGN KEY ("RATE_BOOK_ID") REFERENCES "BE_CARDS"."PC_RATE_BOOK" ("ID");

ALTER TABLE "BE_CARDS"."PC_RATE_FACTOR" ADD CONSTRAINT "FK_PC_27_1" FOREIGN KEY ("RATE_TABLE_ID") REFERENCES "BE_CARDS"."PC_RATE_TABLE" ("ID");

ALTER TABLE "BE_CARDS"."PC_JOB" ADD CONSTRAINT "FK_PC_28_1" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "BE_CARDS"."PC_ACCOUNT" ("ID");

ALTER TABLE "BE_CARDS"."PC_JOB" ADD CONSTRAINT "FK_PC_28_2" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PC_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PC_SUBMISSION" ADD CONSTRAINT "FK_PC_29_1" FOREIGN KEY ("JOB_ID") REFERENCES "BE_CARDS"."PC_JOB" ("ID");

ALTER TABLE "BE_CARDS"."PC_RENEWAL" ADD CONSTRAINT "FK_PC_30_1" FOREIGN KEY ("JOB_ID") REFERENCES "BE_CARDS"."PC_JOB" ("ID");

ALTER TABLE "BE_CARDS"."PC_CANCELLATION" ADD CONSTRAINT "FK_PC_31_1" FOREIGN KEY ("JOB_ID") REFERENCES "BE_CARDS"."PC_JOB" ("ID");

ALTER TABLE "BE_CARDS"."PC_REINSTATEMENT" ADD CONSTRAINT "FK_PC_32_1" FOREIGN KEY ("JOB_ID") REFERENCES "BE_CARDS"."PC_JOB" ("ID");

ALTER TABLE "BE_CARDS"."PC_DOCUMENT" ADD CONSTRAINT "FK_PC_33_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PC_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PC_NOTE" ADD CONSTRAINT "FK_PC_34_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PC_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PC_NOTE" ADD CONSTRAINT "FK_PC_34_2" FOREIGN KEY ("AUTHOR_CONTACT_ID") REFERENCES "BE_CARDS"."PC_CONTACT" ("ID");

ALTER TABLE "BE_CARDS"."PC_ACTIVITY" ADD CONSTRAINT "FK_PC_35_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PC_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PC_WORKFLOW" ADD CONSTRAINT "FK_PC_36_1" FOREIGN KEY ("JOB_ID") REFERENCES "BE_CARDS"."PC_JOB" ("ID");

ALTER TABLE "BE_CARDS"."PC_WORKFLOW_STEP" ADD CONSTRAINT "FK_PC_37_1" FOREIGN KEY ("WORKFLOW_ID") REFERENCES "BE_CARDS"."PC_WORKFLOW" ("ID");

ALTER TABLE "BE_CARDS"."PC_QUESTION" ADD CONSTRAINT "FK_PC_39_1" FOREIGN KEY ("QUESTION_SET_ID") REFERENCES "BE_CARDS"."PC_QUESTION_SET" ("ID");

ALTER TABLE "BE_CARDS"."PC_ANSWER" ADD CONSTRAINT "FK_PC_40_1" FOREIGN KEY ("QUESTION_ID") REFERENCES "BE_CARDS"."PC_QUESTION" ("ID");

ALTER TABLE "BE_CARDS"."PC_ANSWER" ADD CONSTRAINT "FK_PC_40_2" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PC_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PC_PRODUCT_LINE" ADD CONSTRAINT "FK_PC_42_1" FOREIGN KEY ("PRODUCT_ID") REFERENCES "BE_CARDS"."PC_PRODUCT" ("ID");

ALTER TABLE "BE_CARDS"."PC_FORM_PATTERN" ADD CONSTRAINT "FK_PC_43_1" FOREIGN KEY ("PRODUCT_ID") REFERENCES "BE_CARDS"."PC_PRODUCT" ("ID");

ALTER TABLE "BE_CARDS"."PC_POLICY_FORM" ADD CONSTRAINT "FK_PC_44_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PC_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PC_POLICY_FORM" ADD CONSTRAINT "FK_PC_44_2" FOREIGN KEY ("FORM_PATTERN_ID") REFERENCES "BE_CARDS"."PC_FORM_PATTERN" ("ID");

ALTER TABLE "BE_CARDS"."PC_PRODUCER" ADD CONSTRAINT "FK_PC_45_1" FOREIGN KEY ("CONTACT_ID") REFERENCES "BE_CARDS"."PC_CONTACT" ("ID");

ALTER TABLE "BE_CARDS"."PC_PRODUCER_CODE" ADD CONSTRAINT "FK_PC_46_1" FOREIGN KEY ("PRODUCER_ID") REFERENCES "BE_CARDS"."PC_PRODUCER" ("ID");

ALTER TABLE "BE_CARDS"."PC_AUDIT" ADD CONSTRAINT "FK_PC_48_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PC_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PC_MESSAGE_OUTBOX" ADD CONSTRAINT "FK_PC_49_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PC_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PC_CHANGE_EVENT" ADD CONSTRAINT "FK_PC_50_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PC_POLICY_PERIOD" ("ID");
