CREATE TABLE "BE_CARDS"."PT_CONTACT" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "PARENT_CONTACT_ID" NUMBER(19),
  "PARTY_KEY" VARCHAR2(180) UNIQUE,
  "FIRST_NAME" VARCHAR2(180),
  "LAST_NAME" VARCHAR2(180),
  "DATE_OF_BIRTH" DATE,
  "TAX_IDENTIFIER" VARCHAR2(180),
  CONSTRAINT "PK_PT_1" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_ADDRESS" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "CONTACT_ID" NUMBER(19),
  "ADDRESS_LINE1" VARCHAR2(180),
  "CITY" VARCHAR2(180),
  "STATE_CODE" VARCHAR2(40),
  "POSTAL_CODE" VARCHAR2(40),
  CONSTRAINT "PK_PT_2" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_ACCOUNT" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "PRIMARY_CONTACT_ID" NUMBER(19),
  CONSTRAINT "PK_PT_3" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_ACCOUNT_CONTACT" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "ACCOUNT_ID" NUMBER(19),
  "CONTACT_ID" NUMBER(19),
  "PARTY_KEY" VARCHAR2(180) UNIQUE,
  "FIRST_NAME" VARCHAR2(180),
  "LAST_NAME" VARCHAR2(180),
  "DATE_OF_BIRTH" DATE,
  "TAX_IDENTIFIER" VARCHAR2(180),
  CONSTRAINT "PK_PT_4" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_POLICY" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "ACCOUNT_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PT_5" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PT_DATES_5" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PT_POLICY_PERIOD" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PT_6" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PT_DATES_6" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PT_POLICY_LINE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PT_7" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PT_DATES_7" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PT_PERSONAL_AUTO_LINE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_LINE_ID" NUMBER(19),
  CONSTRAINT "PK_PT_8" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_VEHICLE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "AUTO_LINE_ID" NUMBER(19),
  "VIN" VARCHAR2(180) UNIQUE,
  "VEHICLE_YEAR" NUMBER(10),
  "MAKE_NAME" VARCHAR2(180),
  "MODEL_NAME" VARCHAR2(180),
  CONSTRAINT "PK_PT_9" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_DRIVER" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "AUTO_LINE_ID" NUMBER(19),
  "CONTACT_ID" NUMBER(19),
  "PARTY_KEY" VARCHAR2(180) UNIQUE,
  "FIRST_NAME" VARCHAR2(180),
  "LAST_NAME" VARCHAR2(180),
  "DATE_OF_BIRTH" DATE,
  "TAX_IDENTIFIER" VARCHAR2(180),
  CONSTRAINT "PK_PT_10" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_VEHICLE_DRIVER" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "VEHICLE_ID" NUMBER(19),
  "DRIVER_ID" NUMBER(19),
  "PARTY_KEY" VARCHAR2(180) UNIQUE,
  "FIRST_NAME" VARCHAR2(180),
  "LAST_NAME" VARCHAR2(180),
  "DATE_OF_BIRTH" DATE,
  "TAX_IDENTIFIER" VARCHAR2(180),
  "VIN" VARCHAR2(180) UNIQUE,
  "VEHICLE_YEAR" NUMBER(10),
  "MAKE_NAME" VARCHAR2(180),
  "MODEL_NAME" VARCHAR2(180),
  CONSTRAINT "PK_PT_11" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_COVERAGE_PATTERN" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  CONSTRAINT "PK_PT_12" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_COVERAGE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_LINE_ID" NUMBER(19),
  "PATTERN_ID" NUMBER(19),
  CONSTRAINT "PK_PT_13" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_COVERAGE_TERM" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "COVERAGE_ID" NUMBER(19),
  "FACTOR_PERCENT" NUMBER(5,2),
  CONSTRAINT "PK_PT_14" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PT_PCT_14" CHECK ("FACTOR_PERCENT" IS NULL OR ("FACTOR_PERCENT" >= 0 AND "FACTOR_PERCENT" <= 100))
);

CREATE TABLE "BE_CARDS"."PT_LOCATION" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "ACCOUNT_ID" NUMBER(19),
  "ADDRESS_ID" NUMBER(19),
  "ADDRESS_LINE1" VARCHAR2(180),
  "CITY" VARCHAR2(180),
  "STATE_CODE" VARCHAR2(40),
  "POSTAL_CODE" VARCHAR2(40),
  CONSTRAINT "PK_PT_15" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_BUILDING" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "LOCATION_ID" NUMBER(19),
  "ADDRESS_LINE1" VARCHAR2(180),
  "CITY" VARCHAR2(180),
  "STATE_CODE" VARCHAR2(40),
  "POSTAL_CODE" VARCHAR2(40),
  CONSTRAINT "PK_PT_16" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_HOMEOWNERS_LINE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_LINE_ID" NUMBER(19),
  CONSTRAINT "PK_PT_17" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_DWELLING" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "HOME_LINE_ID" NUMBER(19),
  "BUILDING_ID" NUMBER(19),
  "ADDRESS_LINE1" VARCHAR2(180),
  "CITY" VARCHAR2(180),
  "STATE_CODE" VARCHAR2(40),
  "POSTAL_CODE" VARCHAR2(40),
  CONSTRAINT "PK_PT_18" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_POLICY_CONTACT_ROLE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "CONTACT_ID" NUMBER(19),
  "PARTY_KEY" VARCHAR2(180) UNIQUE,
  "FIRST_NAME" VARCHAR2(180),
  "LAST_NAME" VARCHAR2(180),
  "DATE_OF_BIRTH" DATE,
  "TAX_IDENTIFIER" VARCHAR2(180),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PT_19" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PT_DATES_19" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PT_UNDERWRITING_ISSUE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  CONSTRAINT "PK_PT_20" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_UNDERWRITING_REFERRAL" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "ISSUE_ID" NUMBER(19),
  CONSTRAINT "PK_PT_21" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_QUOTE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PT_22" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PT_DATES_22" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PT_QUOTE_COST" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "QUOTE_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  "AMOUNT" NUMBER(18,2),
  "CURRENCY_CODE" VARCHAR2(40),
  CONSTRAINT "PK_PT_23" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PT_AMT_23" CHECK ("AMOUNT" IS NULL OR "AMOUNT" >= 0),
  CONSTRAINT "CK_PT_DATES_23" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PT_PREMIUM_TRANSACTION" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "AMOUNT" NUMBER(18,2),
  "CURRENCY_CODE" VARCHAR2(40),
  CONSTRAINT "PK_PT_24" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PT_AMT_24" CHECK ("AMOUNT" IS NULL OR "AMOUNT" >= 0)
);

CREATE TABLE "BE_CARDS"."PT_RATE_BOOK" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  CONSTRAINT "PK_PT_25" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_RATE_TABLE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "RATE_BOOK_ID" NUMBER(19),
  CONSTRAINT "PK_PT_26" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_RATE_FACTOR" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "RATE_TABLE_ID" NUMBER(19),
  "FACTOR_PERCENT" NUMBER(5,2),
  CONSTRAINT "PK_PT_27" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PT_PCT_27" CHECK ("FACTOR_PERCENT" IS NULL OR ("FACTOR_PERCENT" >= 0 AND "FACTOR_PERCENT" <= 100))
);

CREATE TABLE "BE_CARDS"."PT_JOB" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "ACCOUNT_ID" NUMBER(19),
  "POLICY_PERIOD_ID" NUMBER(19),
  CONSTRAINT "PK_PT_28" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_SUBMISSION" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "JOB_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PT_29" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PT_DATES_29" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PT_RENEWAL" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "JOB_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PT_30" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PT_DATES_30" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PT_CANCELLATION" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "JOB_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PT_31" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PT_DATES_31" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PT_REINSTATEMENT" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "JOB_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PT_32" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PT_DATES_32" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PT_DOCUMENT" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "FILE_NAME" VARCHAR2(180),
  "MIME_TYPE" VARCHAR2(180),
  "DOCUMENT_BODY" BLOB,
  CONSTRAINT "PK_PT_33" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_NOTE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "AUTHOR_CONTACT_ID" NUMBER(19),
  "DETAIL_TEXT" CLOB,
  "PAYLOAD_JSON" CLOB,
  CONSTRAINT "PK_PT_34" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_ACTIVITY" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  CONSTRAINT "PK_PT_35" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_WORKFLOW" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "JOB_ID" NUMBER(19),
  "DETAIL_TEXT" CLOB,
  "PAYLOAD_JSON" CLOB,
  CONSTRAINT "PK_PT_36" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_WORKFLOW_STEP" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "WORKFLOW_ID" NUMBER(19),
  "DETAIL_TEXT" CLOB,
  "PAYLOAD_JSON" CLOB,
  CONSTRAINT "PK_PT_37" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_QUESTION_SET" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  CONSTRAINT "PK_PT_38" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_QUESTION" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "QUESTION_SET_ID" NUMBER(19),
  CONSTRAINT "PK_PT_39" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_ANSWER" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "QUESTION_ID" NUMBER(19),
  "POLICY_PERIOD_ID" NUMBER(19),
  CONSTRAINT "PK_PT_40" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_PRODUCT" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PT_41" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PT_DATES_41" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PT_PRODUCT_LINE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "PRODUCT_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PT_42" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PT_DATES_42" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PT_FORM_PATTERN" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "PRODUCT_ID" NUMBER(19),
  CONSTRAINT "PK_PT_43" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_POLICY_FORM" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "FORM_PATTERN_ID" NUMBER(19),
  "POLICY_NUMBER" VARCHAR2(180),
  "EFFECTIVE_DATE" DATE,
  "EXPIRATION_DATE" DATE,
  CONSTRAINT "PK_PT_44" PRIMARY KEY ("ID"),
  CONSTRAINT "CK_PT_DATES_44" CHECK ("EXPIRATION_DATE" IS NULL OR "EFFECTIVE_DATE" IS NULL OR "EXPIRATION_DATE" >= "EFFECTIVE_DATE")
);

CREATE TABLE "BE_CARDS"."PT_PRODUCER" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "CONTACT_ID" NUMBER(19),
  "PARTY_KEY" VARCHAR2(180) UNIQUE,
  "FIRST_NAME" VARCHAR2(180),
  "LAST_NAME" VARCHAR2(180),
  "DATE_OF_BIRTH" DATE,
  "TAX_IDENTIFIER" VARCHAR2(180),
  CONSTRAINT "PK_PT_45" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_PRODUCER_CODE" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "PRODUCER_ID" NUMBER(19),
  "PARTY_KEY" VARCHAR2(180) UNIQUE,
  "FIRST_NAME" VARCHAR2(180),
  "LAST_NAME" VARCHAR2(180),
  "DATE_OF_BIRTH" DATE,
  "TAX_IDENTIFIER" VARCHAR2(180),
  CONSTRAINT "PK_PT_46" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_TERRITORY" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  CONSTRAINT "PK_PT_47" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_AUDIT" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "DETAIL_TEXT" CLOB,
  "PAYLOAD_JSON" CLOB,
  CONSTRAINT "PK_PT_48" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_MESSAGE_OUTBOX" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "DETAIL_TEXT" CLOB,
  "PAYLOAD_JSON" CLOB,
  CONSTRAINT "PK_PT_49" PRIMARY KEY ("ID")
);

CREATE TABLE "BE_CARDS"."PT_CHANGE_EVENT" (
  "ID" NUMBER(19) NOT NULL,
  "PUBLIC_ID" VARCHAR2(180) NOT NULL UNIQUE,
  "TENANT_ID" VARCHAR2(40),
  "STATUS_CODE" VARCHAR2(40),
  "VERSION_NO" NUMBER(10),
  "RETIRED" NUMBER(1),
  "CREATED_AT" TIMESTAMP WITH TIME ZONE,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE,
  "POLICY_PERIOD_ID" NUMBER(19),
  "DETAIL_TEXT" CLOB,
  "PAYLOAD_JSON" CLOB,
  CONSTRAINT "PK_PT_50" PRIMARY KEY ("ID")
);

ALTER TABLE "BE_CARDS"."PT_CONTACT" ADD CONSTRAINT "FK_PT_1_1" FOREIGN KEY ("PARENT_CONTACT_ID") REFERENCES "BE_CARDS"."PT_CONTACT" ("ID");

ALTER TABLE "BE_CARDS"."PT_ADDRESS" ADD CONSTRAINT "FK_PT_2_1" FOREIGN KEY ("CONTACT_ID") REFERENCES "BE_CARDS"."PT_CONTACT" ("ID");

ALTER TABLE "BE_CARDS"."PT_ACCOUNT" ADD CONSTRAINT "FK_PT_3_1" FOREIGN KEY ("PRIMARY_CONTACT_ID") REFERENCES "BE_CARDS"."PT_CONTACT" ("ID");

ALTER TABLE "BE_CARDS"."PT_ACCOUNT_CONTACT" ADD CONSTRAINT "FK_PT_4_1" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "BE_CARDS"."PT_ACCOUNT" ("ID");

ALTER TABLE "BE_CARDS"."PT_ACCOUNT_CONTACT" ADD CONSTRAINT "FK_PT_4_2" FOREIGN KEY ("CONTACT_ID") REFERENCES "BE_CARDS"."PT_CONTACT" ("ID");

ALTER TABLE "BE_CARDS"."PT_POLICY" ADD CONSTRAINT "FK_PT_5_1" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "BE_CARDS"."PT_ACCOUNT" ("ID");

ALTER TABLE "BE_CARDS"."PT_POLICY_PERIOD" ADD CONSTRAINT "FK_PT_6_1" FOREIGN KEY ("POLICY_ID") REFERENCES "BE_CARDS"."PT_POLICY" ("ID");

ALTER TABLE "BE_CARDS"."PT_POLICY_LINE" ADD CONSTRAINT "FK_PT_7_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PT_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PT_PERSONAL_AUTO_LINE" ADD CONSTRAINT "FK_PT_8_1" FOREIGN KEY ("POLICY_LINE_ID") REFERENCES "BE_CARDS"."PT_POLICY_LINE" ("ID");

ALTER TABLE "BE_CARDS"."PT_VEHICLE" ADD CONSTRAINT "FK_PT_9_1" FOREIGN KEY ("AUTO_LINE_ID") REFERENCES "BE_CARDS"."PT_PERSONAL_AUTO_LINE" ("ID");

ALTER TABLE "BE_CARDS"."PT_DRIVER" ADD CONSTRAINT "FK_PT_10_1" FOREIGN KEY ("AUTO_LINE_ID") REFERENCES "BE_CARDS"."PT_PERSONAL_AUTO_LINE" ("ID");

ALTER TABLE "BE_CARDS"."PT_DRIVER" ADD CONSTRAINT "FK_PT_10_2" FOREIGN KEY ("CONTACT_ID") REFERENCES "BE_CARDS"."PT_CONTACT" ("ID");

ALTER TABLE "BE_CARDS"."PT_VEHICLE_DRIVER" ADD CONSTRAINT "FK_PT_11_1" FOREIGN KEY ("VEHICLE_ID") REFERENCES "BE_CARDS"."PT_VEHICLE" ("ID");

ALTER TABLE "BE_CARDS"."PT_VEHICLE_DRIVER" ADD CONSTRAINT "FK_PT_11_2" FOREIGN KEY ("DRIVER_ID") REFERENCES "BE_CARDS"."PT_DRIVER" ("ID");

ALTER TABLE "BE_CARDS"."PT_COVERAGE" ADD CONSTRAINT "FK_PT_13_1" FOREIGN KEY ("POLICY_LINE_ID") REFERENCES "BE_CARDS"."PT_POLICY_LINE" ("ID");

ALTER TABLE "BE_CARDS"."PT_COVERAGE" ADD CONSTRAINT "FK_PT_13_2" FOREIGN KEY ("PATTERN_ID") REFERENCES "BE_CARDS"."PT_COVERAGE_PATTERN" ("ID");

ALTER TABLE "BE_CARDS"."PT_COVERAGE_TERM" ADD CONSTRAINT "FK_PT_14_1" FOREIGN KEY ("COVERAGE_ID") REFERENCES "BE_CARDS"."PT_COVERAGE" ("ID");

ALTER TABLE "BE_CARDS"."PT_LOCATION" ADD CONSTRAINT "FK_PT_15_1" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "BE_CARDS"."PT_ACCOUNT" ("ID");

ALTER TABLE "BE_CARDS"."PT_LOCATION" ADD CONSTRAINT "FK_PT_15_2" FOREIGN KEY ("ADDRESS_ID") REFERENCES "BE_CARDS"."PT_ADDRESS" ("ID");

ALTER TABLE "BE_CARDS"."PT_BUILDING" ADD CONSTRAINT "FK_PT_16_1" FOREIGN KEY ("LOCATION_ID") REFERENCES "BE_CARDS"."PT_LOCATION" ("ID");

ALTER TABLE "BE_CARDS"."PT_HOMEOWNERS_LINE" ADD CONSTRAINT "FK_PT_17_1" FOREIGN KEY ("POLICY_LINE_ID") REFERENCES "BE_CARDS"."PT_POLICY_LINE" ("ID");

ALTER TABLE "BE_CARDS"."PT_DWELLING" ADD CONSTRAINT "FK_PT_18_1" FOREIGN KEY ("HOME_LINE_ID") REFERENCES "BE_CARDS"."PT_HOMEOWNERS_LINE" ("ID");

ALTER TABLE "BE_CARDS"."PT_DWELLING" ADD CONSTRAINT "FK_PT_18_2" FOREIGN KEY ("BUILDING_ID") REFERENCES "BE_CARDS"."PT_BUILDING" ("ID");

ALTER TABLE "BE_CARDS"."PT_POLICY_CONTACT_ROLE" ADD CONSTRAINT "FK_PT_19_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PT_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PT_POLICY_CONTACT_ROLE" ADD CONSTRAINT "FK_PT_19_2" FOREIGN KEY ("CONTACT_ID") REFERENCES "BE_CARDS"."PT_CONTACT" ("ID");

ALTER TABLE "BE_CARDS"."PT_UNDERWRITING_ISSUE" ADD CONSTRAINT "FK_PT_20_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PT_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PT_UNDERWRITING_REFERRAL" ADD CONSTRAINT "FK_PT_21_1" FOREIGN KEY ("ISSUE_ID") REFERENCES "BE_CARDS"."PT_UNDERWRITING_ISSUE" ("ID");

ALTER TABLE "BE_CARDS"."PT_QUOTE" ADD CONSTRAINT "FK_PT_22_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PT_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PT_QUOTE_COST" ADD CONSTRAINT "FK_PT_23_1" FOREIGN KEY ("QUOTE_ID") REFERENCES "BE_CARDS"."PT_QUOTE" ("ID");

ALTER TABLE "BE_CARDS"."PT_PREMIUM_TRANSACTION" ADD CONSTRAINT "FK_PT_24_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PT_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PT_RATE_TABLE" ADD CONSTRAINT "FK_PT_26_1" FOREIGN KEY ("RATE_BOOK_ID") REFERENCES "BE_CARDS"."PT_RATE_BOOK" ("ID");

ALTER TABLE "BE_CARDS"."PT_RATE_FACTOR" ADD CONSTRAINT "FK_PT_27_1" FOREIGN KEY ("RATE_TABLE_ID") REFERENCES "BE_CARDS"."PT_RATE_TABLE" ("ID");

ALTER TABLE "BE_CARDS"."PT_JOB" ADD CONSTRAINT "FK_PT_28_1" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "BE_CARDS"."PT_ACCOUNT" ("ID");

ALTER TABLE "BE_CARDS"."PT_JOB" ADD CONSTRAINT "FK_PT_28_2" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PT_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PT_SUBMISSION" ADD CONSTRAINT "FK_PT_29_1" FOREIGN KEY ("JOB_ID") REFERENCES "BE_CARDS"."PT_JOB" ("ID");

ALTER TABLE "BE_CARDS"."PT_RENEWAL" ADD CONSTRAINT "FK_PT_30_1" FOREIGN KEY ("JOB_ID") REFERENCES "BE_CARDS"."PT_JOB" ("ID");

ALTER TABLE "BE_CARDS"."PT_CANCELLATION" ADD CONSTRAINT "FK_PT_31_1" FOREIGN KEY ("JOB_ID") REFERENCES "BE_CARDS"."PT_JOB" ("ID");

ALTER TABLE "BE_CARDS"."PT_REINSTATEMENT" ADD CONSTRAINT "FK_PT_32_1" FOREIGN KEY ("JOB_ID") REFERENCES "BE_CARDS"."PT_JOB" ("ID");

ALTER TABLE "BE_CARDS"."PT_DOCUMENT" ADD CONSTRAINT "FK_PT_33_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PT_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PT_NOTE" ADD CONSTRAINT "FK_PT_34_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PT_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PT_NOTE" ADD CONSTRAINT "FK_PT_34_2" FOREIGN KEY ("AUTHOR_CONTACT_ID") REFERENCES "BE_CARDS"."PT_CONTACT" ("ID");

ALTER TABLE "BE_CARDS"."PT_ACTIVITY" ADD CONSTRAINT "FK_PT_35_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PT_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PT_WORKFLOW" ADD CONSTRAINT "FK_PT_36_1" FOREIGN KEY ("JOB_ID") REFERENCES "BE_CARDS"."PT_JOB" ("ID");

ALTER TABLE "BE_CARDS"."PT_WORKFLOW_STEP" ADD CONSTRAINT "FK_PT_37_1" FOREIGN KEY ("WORKFLOW_ID") REFERENCES "BE_CARDS"."PT_WORKFLOW" ("ID");

ALTER TABLE "BE_CARDS"."PT_QUESTION" ADD CONSTRAINT "FK_PT_39_1" FOREIGN KEY ("QUESTION_SET_ID") REFERENCES "BE_CARDS"."PT_QUESTION_SET" ("ID");

ALTER TABLE "BE_CARDS"."PT_ANSWER" ADD CONSTRAINT "FK_PT_40_1" FOREIGN KEY ("QUESTION_ID") REFERENCES "BE_CARDS"."PT_QUESTION" ("ID");

ALTER TABLE "BE_CARDS"."PT_ANSWER" ADD CONSTRAINT "FK_PT_40_2" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PT_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PT_PRODUCT_LINE" ADD CONSTRAINT "FK_PT_42_1" FOREIGN KEY ("PRODUCT_ID") REFERENCES "BE_CARDS"."PT_PRODUCT" ("ID");

ALTER TABLE "BE_CARDS"."PT_FORM_PATTERN" ADD CONSTRAINT "FK_PT_43_1" FOREIGN KEY ("PRODUCT_ID") REFERENCES "BE_CARDS"."PT_PRODUCT" ("ID");

ALTER TABLE "BE_CARDS"."PT_POLICY_FORM" ADD CONSTRAINT "FK_PT_44_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PT_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PT_POLICY_FORM" ADD CONSTRAINT "FK_PT_44_2" FOREIGN KEY ("FORM_PATTERN_ID") REFERENCES "BE_CARDS"."PT_FORM_PATTERN" ("ID");

ALTER TABLE "BE_CARDS"."PT_PRODUCER" ADD CONSTRAINT "FK_PT_45_1" FOREIGN KEY ("CONTACT_ID") REFERENCES "BE_CARDS"."PT_CONTACT" ("ID");

ALTER TABLE "BE_CARDS"."PT_PRODUCER_CODE" ADD CONSTRAINT "FK_PT_46_1" FOREIGN KEY ("PRODUCER_ID") REFERENCES "BE_CARDS"."PT_PRODUCER" ("ID");

ALTER TABLE "BE_CARDS"."PT_AUDIT" ADD CONSTRAINT "FK_PT_48_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PT_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PT_MESSAGE_OUTBOX" ADD CONSTRAINT "FK_PT_49_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PT_POLICY_PERIOD" ("ID");

ALTER TABLE "BE_CARDS"."PT_CHANGE_EVENT" ADD CONSTRAINT "FK_PT_50_1" FOREIGN KEY ("POLICY_PERIOD_ID") REFERENCES "BE_CARDS"."PT_POLICY_PERIOD" ("ID");
