DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS addresses;
DROP TABLE IF EXISTS customers;

CREATE TABLE customers (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name   VARCHAR(60)  NOT NULL,
  last_name    VARCHAR(60)  NOT NULL,
  email        VARCHAR(120) NOT NULL,
  phone        VARCHAR(30),
  ssn          VARCHAR(11)  NOT NULL,
  dob          DATE         NOT NULL,
  vip          BOOLEAN DEFAULT FALSE,
  status       VARCHAR(15) DEFAULT 'ACTIVE'
);

CREATE TABLE addresses (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  BIGINT NOT NULL REFERENCES customers(id),
  street_addr  VARCHAR(120) NOT NULL,
  city         VARCHAR(60) NOT NULL,
  state        VARCHAR(2) NOT NULL,
  zip          VARCHAR(10) NOT NULL,
  address_type VARCHAR(20) DEFAULT 'HOME'
);

CREATE TABLE accounts (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  BIGINT NOT NULL REFERENCES customers(id),
  account_no   VARCHAR(20) NOT NULL,
  account_type VARCHAR(20) NOT NULL,
  balance      NUMERIC(12,2) DEFAULT 0,
  status       VARCHAR(15) DEFAULT 'ACTIVE',
  opened_on    DATE NOT NULL
);

CREATE TABLE cards (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id      BIGINT NOT NULL REFERENCES accounts(id),
  card_number     VARCHAR(25) NOT NULL,
  cardholder_name VARCHAR(120) NOT NULL,
  expiry_month    INT NOT NULL,
  expiry_year     INT NOT NULL,
  status          VARCHAR(15) DEFAULT 'ACTIVE'
);

CREATE TABLE transactions (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id   BIGINT NOT NULL REFERENCES accounts(id),
  amount       NUMERIC(12,2) NOT NULL,
  tx_date      DATE NOT NULL,
  merchant     VARCHAR(120),
  category     VARCHAR(40),
  memo         VARCHAR(200)
);

ALTER USER demo ADMIN TRUE;
GRANT ALL ON SCHEMA public TO demo;
GRANT ALL ON TABLE customers TO demo;
GRANT ALL ON TABLE addresses TO demo;
GRANT ALL ON TABLE accounts TO demo;
GRANT ALL ON TABLE cards TO demo;
GRANT ALL ON TABLE transactions TO demo;
