ALTER TABLE synthetic_saved_jobs
  ADD COLUMN approval_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT';

ALTER TABLE synthetic_saved_jobs
  ADD COLUMN approval_requested_at TIMESTAMP;

ALTER TABLE synthetic_saved_jobs
  ADD COLUMN approved_at TIMESTAMP;

ALTER TABLE synthetic_saved_jobs
  ADD COLUMN approved_by VARCHAR(120);

ALTER TABLE synthetic_saved_jobs
  ADD COLUMN approval_note TEXT;

ALTER TABLE synthetic_generation_jobs
  ADD COLUMN plan_hash VARCHAR(128);

ALTER TABLE synthetic_generation_jobs
  ADD COLUMN lineage_json TEXT;

ALTER TABLE synthetic_generation_jobs
  ADD COLUMN constraint_snapshot_json TEXT;

ALTER TABLE synthetic_generation_jobs
  ADD COLUMN approval_snapshot_json TEXT;

CREATE TABLE synthetic_generation_lineage (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id                   VARCHAR(80) NOT NULL,
  saved_job_id             VARCHAR(80),
  saved_job_name           VARCHAR(200),
  owner_username           VARCHAR(120),
  plan_hash                VARCHAR(128),
  dataset                  VARCHAR(200),
  receiver                 VARCHAR(30),
  target_data_source_id    BIGINT,
  target_schema            VARCHAR(200),
  row_count                BIGINT,
  table_count              INTEGER,
  seed_value               BIGINT,
  approval_status          VARCHAR(30),
  approved_by              VARCHAR(120),
  approved_at              TIMESTAMP,
  constraint_snapshot_json TEXT,
  plan_summary_json        TEXT,
  created_at               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_synthetic_lineage_job ON synthetic_generation_lineage(job_id);
CREATE INDEX idx_synthetic_lineage_saved_job ON synthetic_generation_lineage(saved_job_id, created_at DESC);
