-- User-defined masking scripts (Optim-style Lua exits): custom logic for anything the built-in
-- functions don't cover. Referenced from a policy rule as function SCRIPT with param1 = script name.
CREATE TABLE masking_scripts (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(120) NOT NULL UNIQUE,   -- lower-case handle used in the rule's param1
  description    VARCHAR(400),
  lua_source     TEXT NOT NULL,
  owner_username VARCHAR(120),
  visibility     VARCHAR(20) NOT NULL DEFAULT 'GLOBAL',   -- GLOBAL (usable in jobs) | PRIVATE (draft)
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
