-- Named, centrally maintained value lists (reference data domains) for synthetic generation.
-- Referenced from generator params as @name (e.g. ENUM param1 = @bank-a.product_type) and resolved
-- at run time, so updating the list here updates every plan that references it.
CREATE TABLE synthetic_value_lists (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(120) NOT NULL UNIQUE,   -- lower-case handle, e.g. bank-a.product_type
  description    VARCHAR(400),
  system_tag     VARCHAR(80),                    -- which system/customer owns these values, e.g. bank-a
  list_values    TEXT NOT NULL,                  -- pipe syntax: A1|A2|A3 or weighted A1:60|A2:30|A3:10
  owner_username VARCHAR(120),
  visibility     VARCHAR(20) NOT NULL DEFAULT 'GLOBAL',   -- GLOBAL | PRIVATE
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_value_lists_system ON synthetic_value_lists(system_tag);
