-- Workflow orchestration (Informatica-style): ordered steps (saved mappings / raw SQL) executed
-- server-side with per-step status and STOP/CONTINUE failure policy. last_run_json holds the most
-- recent run's per-step results for the UI.
CREATE TABLE mapping_workflows (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(200) NOT NULL UNIQUE,
    description   TEXT,
    steps_json    TEXT NOT NULL,
    last_run_json TEXT,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
