-- Row-oriented lookup catalog used by DIRECT_LOOKUP and HASH_LOOKUP.
-- HASH rows use contiguous positive keys; -1/-2/-3 are reserved for NULL/spaces/zero-length input.
CREATE TABLE masking_lookup_values (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lookup_name       VARCHAR(120) NOT NULL,
  lookup_mode       VARCHAR(16) NOT NULL,
  lookup_key        INTEGER,
  source_value      VARCHAR(512),
  replacement_value VARCHAR(512) NOT NULL,
  description       VARCHAR(400),
  created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_mask_lookup_name_mode ON masking_lookup_values(lookup_name, lookup_mode);
CREATE UNIQUE INDEX uq_mask_lookup_hash_key ON masking_lookup_values(lookup_name, lookup_mode, lookup_key);
CREATE UNIQUE INDEX uq_mask_lookup_direct_source ON masking_lookup_values(lookup_name, lookup_mode, source_value);

INSERT INTO masking_lookup_values
  (lookup_name, lookup_mode, lookup_key, replacement_value, description)
VALUES
  ('demo.us-first-names', 'HASH', -1, 'Unknown', 'NULL source value'),
  ('demo.us-first-names', 'HASH', -2, 'Blank', 'Space-only source value'),
  ('demo.us-first-names', 'HASH', -3, 'Empty', 'Zero-length source value'),
  ('demo.us-first-names', 'HASH',  1, 'Olivia', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH',  2, 'Emma', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH',  3, 'Amelia', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH',  4, 'Charlotte', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH',  5, 'Mia', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH',  6, 'Sophia', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH',  7, 'Liam', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH',  8, 'Noah', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH',  9, 'Oliver', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH', 10, 'James', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH', 11, 'Elijah', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH', 12, 'Mateo', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH', 13, 'Ava', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH', 14, 'Isabella', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH', 15, 'Evelyn', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH', 16, 'Lucas', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH', 17, 'Henry', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH', 18, 'Theodore', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH', 19, 'Harper', 'US first-name replacement'),
  ('demo.us-first-names', 'HASH', 20, 'Camila', 'US first-name replacement');

INSERT INTO masking_lookup_values
  (lookup_name, lookup_mode, source_value, replacement_value, description)
VALUES
  ('demo.account-tier', 'DIRECT', '<NULL>', 'UNKNOWN', 'NULL account tier'),
  ('demo.account-tier', 'DIRECT', 'CHK', 'EVERYDAY', 'Checking account'),
  ('demo.account-tier', 'DIRECT', 'SAV', 'RESERVE', 'Savings account'),
  ('demo.account-tier', 'DIRECT', 'MMA', 'PREMIUM_RESERVE', 'Money-market account'),
  ('demo.account-tier', 'DIRECT', 'CD', 'TERM_DEPOSIT', 'Certificate of deposit'),
  ('demo.account-tier', 'DIRECT', 'LOC', 'CREDIT_LINE', 'Line of credit');
