-- Durable enterprise mapping, auto-provision execution evidence, and unstructured masking.

CREATE TABLE mapping_definition_versions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mapping_id    BIGINT NOT NULL,
    version_no    INTEGER NOT NULL,
    name          VARCHAR(200) NOT NULL,
    description   TEXT,
    spec_json     TEXT NOT NULL,
    spec_hash     VARCHAR(64) NOT NULL,
    created_by    VARCHAR(120) NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_mapping_version UNIQUE (mapping_id, version_no)
);

CREATE INDEX idx_mapping_versions_mapping ON mapping_definition_versions(mapping_id, version_no);

CREATE TABLE mapping_file_assets (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(200) NOT NULL,
    format            VARCHAR(30) NOT NULL,
    original_filename VARCHAR(500) NOT NULL,
    content_type      VARCHAR(200),
    size_bytes        BIGINT NOT NULL,
    sha256            VARCHAR(64) NOT NULL,
    storage_key       VARCHAR(100) NOT NULL UNIQUE,
    key_salt          VARCHAR(64) NOT NULL,
    payload_iv        VARCHAR(64) NOT NULL,
    options_json      TEXT NOT NULL,
    schema_json       TEXT NOT NULL,
    created_by        VARCHAR(120) NOT NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_mapping_assets_owner ON mapping_file_assets(created_by, created_at);

CREATE TABLE mapping_execution_runs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mapping_id        BIGINT NOT NULL,
    mapping_version   INTEGER NOT NULL,
    run_type          VARCHAR(40) NOT NULL,
    status            VARCHAR(30) NOT NULL,
    stage             VARCHAR(60) NOT NULL,
    progress          INTEGER NOT NULL DEFAULT 0,
    message           VARCHAR(1000),
    rows_read         BIGINT NOT NULL DEFAULT 0,
    rows_written      BIGINT NOT NULL DEFAULT 0,
    rows_rejected     BIGINT NOT NULL DEFAULT 0,
    request_json      TEXT NOT NULL,
    result_json       TEXT,
    error_message     TEXT,
    output_name       VARCHAR(500),
    output_format     VARCHAR(30),
    output_storage_key VARCHAR(100),
    output_key_salt   VARCHAR(64),
    output_iv         VARCHAR(64),
    output_sha256     VARCHAR(64),
    cancel_requested  BOOLEAN NOT NULL DEFAULT FALSE,
    created_by        VARCHAR(120) NOT NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at        TIMESTAMP,
    finished_at       TIMESTAMP
);

CREATE INDEX idx_mapping_runs_mapping ON mapping_execution_runs(mapping_id, created_at);
CREATE INDEX idx_mapping_runs_owner ON mapping_execution_runs(created_by, created_at);

CREATE TABLE unstructured_masking_profiles (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(200) NOT NULL UNIQUE,
    description   TEXT,
    rules_json    TEXT NOT NULL,
    status        VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    version_no    INTEGER NOT NULL DEFAULT 1,
    created_by    VARCHAR(120) NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE unstructured_masking_jobs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id        BIGINT NOT NULL,
    profile_version   INTEGER NOT NULL,
    original_filename VARCHAR(500) NOT NULL,
    detected_format   VARCHAR(80),
    output_strategy   VARCHAR(80),
    status            VARCHAR(30) NOT NULL,
    stage             VARCHAR(60) NOT NULL,
    progress          INTEGER NOT NULL DEFAULT 0,
    message           VARCHAR(1000),
    bytes_read        BIGINT NOT NULL DEFAULT 0,
    chars_processed   BIGINT NOT NULL DEFAULT 0,
    findings_count    BIGINT NOT NULL DEFAULT 0,
    findings_json     TEXT,
    source_sha256     VARCHAR(64),
    output_sha256     VARCHAR(64),
    source_storage_key VARCHAR(100),
    source_key_salt   VARCHAR(64),
    source_iv         VARCHAR(64),
    output_storage_key VARCHAR(100),
    output_key_salt   VARCHAR(64),
    output_iv         VARCHAR(64),
    output_name       VARCHAR(500),
    error_message     TEXT,
    cancel_requested  BOOLEAN NOT NULL DEFAULT FALSE,
    created_by        VARCHAR(120) NOT NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at        TIMESTAMP,
    finished_at       TIMESTAMP
);

CREATE INDEX idx_unstructured_jobs_owner ON unstructured_masking_jobs(created_by, created_at);
CREATE INDEX idx_unstructured_jobs_profile ON unstructured_masking_jobs(profile_id, created_at);
