CREATE TABLE self_service_products (
  id                       VARCHAR(36) PRIMARY KEY,
  product_type             VARCHAR(40) NOT NULL,
  artifact_id              VARCHAR(120) NOT NULL,
  artifact_version         INTEGER,
  label                    VARCHAR(200) NOT NULL,
  description              VARCHAR(2000),
  category                 VARCHAR(100),
  tags                     VARCHAR(1000),
  owner_user_id            BIGINT,
  owner_username           VARCHAR(120) NOT NULL,
  enabled                  BOOLEAN NOT NULL DEFAULT TRUE,
  approval_mode            VARCHAR(30) NOT NULL DEFAULT 'REQUIRED',
  questionnaire_json       TEXT,
  guardrails_json          TEXT,
  allowed_environments     VARCHAR(1000),
  delivery_instructions    TEXT,
  created_at               TIMESTAMP NOT NULL,
  updated_at               TIMESTAMP NOT NULL,
  UNIQUE(product_type, artifact_id)
);
CREATE INDEX idx_self_service_products_catalog ON self_service_products(enabled, category, product_type);

CREATE TABLE self_service_orders (
  id                       VARCHAR(36) PRIMARY KEY,
  product_id               VARCHAR(36) NOT NULL REFERENCES self_service_products(id),
  product_type             VARCHAR(40) NOT NULL,
  artifact_id              VARCHAR(120) NOT NULL,
  product_label            VARCHAR(200) NOT NULL,
  requested_by_id          BIGINT NOT NULL REFERENCES forge_users(id),
  requested_by             VARCHAR(120) NOT NULL,
  purpose                  VARCHAR(1000) NOT NULL,
  test_type                VARCHAR(80),
  environment              VARCHAR(80),
  parameters_json          TEXT,
  requested_volume         BIGINT,
  requested_variety        VARCHAR(1000),
  delivery_mode            VARCHAR(40),
  reservation_requested    BOOLEAN NOT NULL DEFAULT FALSE,
  reservation_hours        INTEGER,
  schedule_at              TIMESTAMP,
  status                   VARCHAR(40) NOT NULL,
  decision_by_id           BIGINT,
  decision_by              VARCHAR(120),
  decision_note            VARCHAR(1000),
  decided_at               TIMESTAMP,
  run_type                 VARCHAR(40),
  run_ref                  VARCHAR(120),
  result_json              TEXT,
  fulfilled_at             TIMESTAMP,
  canceled_at              TIMESTAMP,
  expires_at               TIMESTAMP,
  created_at               TIMESTAMP NOT NULL,
  updated_at               TIMESTAMP NOT NULL
);
CREATE INDEX idx_self_service_orders_requester ON self_service_orders(requested_by_id, created_at DESC);
CREATE INDEX idx_self_service_orders_queue ON self_service_orders(status, schedule_at, created_at);

CREATE TABLE self_service_order_events (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id                 VARCHAR(36) NOT NULL REFERENCES self_service_orders(id) ON DELETE CASCADE,
  event_type               VARCHAR(60) NOT NULL,
  actor                    VARCHAR(120) NOT NULL,
  message                  VARCHAR(2000),
  detail_json              TEXT,
  created_at               TIMESTAMP NOT NULL
);
CREATE INDEX idx_self_service_order_events ON self_service_order_events(order_id, created_at);
