CREATE TABLE forge_ai_documents (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_key      VARCHAR(300) NOT NULL UNIQUE,
    document_type     VARCHAR(60) NOT NULL,
    origin            VARCHAR(30) NOT NULL DEFAULT 'SYSTEM',
    title             VARCHAR(300) NOT NULL,
    summary           TEXT,
    searchable_text   TEXT NOT NULL,
    metadata_json     TEXT NOT NULL DEFAULT '{}',
    sensitivity       VARCHAR(30) NOT NULL DEFAULT 'METADATA_ONLY',
    content_hash      VARCHAR(64) NOT NULL,
    version_no        INTEGER NOT NULL DEFAULT 1,
    active            BOOLEAN NOT NULL DEFAULT TRUE,
    created_by        VARCHAR(120) NOT NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_forge_ai_documents_type ON forge_ai_documents(document_type, active);
CREATE INDEX idx_forge_ai_documents_updated ON forge_ai_documents(updated_at);

CREATE TABLE forge_ai_store_sync_runs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status            VARCHAR(30) NOT NULL,
    documents_written INTEGER NOT NULL DEFAULT 0,
    source_counts_json TEXT NOT NULL DEFAULT '{}',
    message           VARCHAR(2000),
    triggered_by      VARCHAR(120) NOT NULL,
    started_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at       TIMESTAMP
);

CREATE INDEX idx_forge_ai_store_sync_runs_started ON forge_ai_store_sync_runs(started_at);

CREATE TABLE forge_ai_agent_runs (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal                  TEXT NOT NULL,
    status                VARCHAR(40) NOT NULL,
    summary               TEXT,
    provider_id           VARCHAR(120),
    model_name            VARCHAR(240),
    intent_json           TEXT NOT NULL,
    plan_json             TEXT NOT NULL,
    validation_json       TEXT NOT NULL DEFAULT '[]',
    questions_json        TEXT NOT NULL DEFAULT '[]',
    evidence_json         TEXT NOT NULL DEFAULT '[]',
    confidence            DOUBLE PRECISION NOT NULL DEFAULT 0,
    risk_level            VARCHAR(30) NOT NULL DEFAULT 'MEDIUM',
    plan_fingerprint      VARCHAR(64) NOT NULL,
    model_assisted        BOOLEAN NOT NULL DEFAULT FALSE,
    created_by            VARCHAR(120) NOT NULL,
    approved_by           VARCHAR(120),
    approved_at           TIMESTAMP,
    canceled_at           TIMESTAMP,
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_forge_ai_agent_runs_actor ON forge_ai_agent_runs(created_by, created_at);
CREATE INDEX idx_forge_ai_agent_runs_status ON forge_ai_agent_runs(status, updated_at);

CREATE TABLE forge_ai_agent_steps (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                BIGINT NOT NULL REFERENCES forge_ai_agent_runs(id) ON DELETE CASCADE,
    ordinal_no            INTEGER NOT NULL,
    step_code             VARCHAR(80) NOT NULL,
    title                 VARCHAR(300) NOT NULL,
    detail                TEXT,
    operation             VARCHAR(80) NOT NULL,
    status                VARCHAR(40) NOT NULL,
    changes_data          BOOLEAN NOT NULL DEFAULT FALSE,
    requires_approval     BOOLEAN NOT NULL DEFAULT FALSE,
    action_name           VARCHAR(120),
    action_args_json      TEXT,
    action_summary        TEXT,
    evidence_json         TEXT NOT NULL DEFAULT '[]',
    result_json           TEXT,
    started_at            TIMESTAMP,
    finished_at           TIMESTAMP,
    updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(run_id, ordinal_no)
);

CREATE INDEX idx_forge_ai_agent_steps_run ON forge_ai_agent_steps(run_id, ordinal_no);

CREATE TABLE forge_ai_agent_events (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id            BIGINT NOT NULL REFERENCES forge_ai_agent_runs(id) ON DELETE CASCADE,
    event_type        VARCHAR(80) NOT NULL,
    actor             VARCHAR(120) NOT NULL,
    message           VARCHAR(2000),
    detail_json       TEXT NOT NULL DEFAULT '{}',
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_forge_ai_agent_events_run ON forge_ai_agent_events(run_id, created_at);

CREATE TABLE forge_ai_plan_feedback (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id            BIGINT NOT NULL REFERENCES forge_ai_agent_runs(id) ON DELETE CASCADE,
    rating            INTEGER,
    accepted          BOOLEAN,
    correction_json   TEXT,
    comment_text      TEXT,
    submitted_by      VARCHAR(120) NOT NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_forge_ai_feedback_rating CHECK (rating IS NULL OR (rating >= 1 AND rating <= 5))
);

CREATE INDEX idx_forge_ai_plan_feedback_run ON forge_ai_plan_feedback(run_id, created_at);
