-- Governed enterprise data topology.
--
-- Discovery writes operation-scoped graph rows. topology_models.current_operation_id is
-- advanced only after a complete capture, so cancellation or source failure never replaces
-- the last known-good graph.

CREATE TABLE IF NOT EXISTS topology_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    domain VARCHAR(80),
    description VARCHAR(1000),
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    current_operation_id BIGINT,
    current_hash VARCHAR(64),
    current_version INTEGER NOT NULL DEFAULT 0,
    lock_version BIGINT NOT NULL DEFAULT 0,
    owner_user_id BIGINT REFERENCES forge_users(id) ON DELETE SET NULL,
    owner_username VARCHAR(120),
    owner_group_id BIGINT REFERENCES forge_groups(id) ON DELETE SET NULL,
    visibility VARCHAR(16) NOT NULL DEFAULT 'GROUP',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_topology_models_tenancy
    ON topology_models (visibility, owner_group_id, owner_user_id);
CREATE INDEX IF NOT EXISTS idx_topology_models_updated
    ON topology_models (updated_at DESC);

CREATE TABLE IF NOT EXISTS topology_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topology_id BIGINT NOT NULL REFERENCES topology_models(id) ON DELETE CASCADE,
    data_source_id BIGINT NOT NULL REFERENCES data_sources(id) ON DELETE RESTRICT,
    schema_name VARCHAR(256) NOT NULL,
    application_label VARCHAR(120),
    provider_mode VARCHAR(40),
    captured_at TIMESTAMPTZ,
    node_count INTEGER NOT NULL DEFAULT 0,
    edge_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (topology_id, data_source_id, schema_name)
);

CREATE INDEX IF NOT EXISTS idx_topology_sources_model
    ON topology_sources (topology_id, data_source_id);

CREATE TABLE IF NOT EXISTS topology_discovery_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topology_id BIGINT NOT NULL REFERENCES topology_models(id) ON DELETE CASCADE,
    status VARCHAR(24) NOT NULL DEFAULT 'QUEUED',
    percent INTEGER NOT NULL DEFAULT 0,
    completed_sources INTEGER NOT NULL DEFAULT 0,
    total_sources INTEGER NOT NULL DEFAULT 0,
    completed_objects INTEGER NOT NULL DEFAULT 0,
    total_objects INTEGER NOT NULL DEFAULT 0,
    current_source VARCHAR(120),
    active_schema VARCHAR(256),
    current_object VARCHAR(256),
    message VARCHAR(1000),
    error_message VARCHAR(2000),
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    requested_by VARCHAR(120),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_topology_discovery_model
    ON topology_discovery_operations (topology_id, created_at DESC);

CREATE TABLE IF NOT EXISTS topology_nodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topology_id BIGINT NOT NULL REFERENCES topology_models(id) ON DELETE CASCADE,
    operation_id BIGINT NOT NULL REFERENCES topology_discovery_operations(id) ON DELETE CASCADE,
    source_binding_id BIGINT NOT NULL REFERENCES topology_sources(id) ON DELETE CASCADE,
    stable_key VARCHAR(900) NOT NULL,
    catalog_name VARCHAR(256),
    schema_name VARCHAR(256) NOT NULL,
    object_name VARCHAR(256) NOT NULL,
    object_type VARCHAR(32) NOT NULL,
    column_count INTEGER NOT NULL DEFAULT 0,
    primary_key_count INTEGER NOT NULL DEFAULT 0,
    row_estimate BIGINT,
    metadata_json TEXT,
    UNIQUE (operation_id, stable_key)
);

CREATE INDEX IF NOT EXISTS idx_topology_nodes_graph
    ON topology_nodes (topology_id, operation_id, source_binding_id);
CREATE INDEX IF NOT EXISTS idx_topology_nodes_name
    ON topology_nodes (topology_id, schema_name, object_name);

CREATE TABLE IF NOT EXISTS topology_columns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id BIGINT NOT NULL REFERENCES topology_nodes(id) ON DELETE CASCADE,
    ordinal_position INTEGER NOT NULL,
    column_name VARCHAR(256) NOT NULL,
    data_type VARCHAR(256),
    jdbc_type INTEGER,
    length_value BIGINT,
    scale_value INTEGER,
    nullable BOOLEAN NOT NULL DEFAULT TRUE,
    primary_key BOOLEAN NOT NULL DEFAULT FALSE,
    unique_key BOOLEAN NOT NULL DEFAULT FALSE,
    generated_column BOOLEAN NOT NULL DEFAULT FALSE,
    default_expression VARCHAR(1000),
    UNIQUE (node_id, column_name)
);

CREATE INDEX IF NOT EXISTS idx_topology_columns_node
    ON topology_columns (node_id, ordinal_position);

CREATE TABLE IF NOT EXISTS topology_edges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topology_id BIGINT NOT NULL REFERENCES topology_models(id) ON DELETE CASCADE,
    operation_id BIGINT NOT NULL REFERENCES topology_discovery_operations(id) ON DELETE CASCADE,
    source_binding_id BIGINT NOT NULL REFERENCES topology_sources(id) ON DELETE CASCADE,
    stable_key VARCHAR(1200) NOT NULL,
    constraint_name VARCHAR(256),
    child_node_id BIGINT NOT NULL REFERENCES topology_nodes(id) ON DELETE CASCADE,
    parent_node_id BIGINT NOT NULL REFERENCES topology_nodes(id) ON DELETE CASCADE,
    child_columns VARCHAR(2000) NOT NULL,
    parent_columns VARCHAR(2000) NOT NULL,
    evidence_type VARCHAR(32) NOT NULL,
    decision_status VARCHAR(24) NOT NULL,
    confidence INTEGER NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    evidence_json TEXT,
    reviewed_by VARCHAR(120),
    reviewed_at TIMESTAMPTZ,
    UNIQUE (operation_id, stable_key)
);

CREATE INDEX IF NOT EXISTS idx_topology_edges_graph
    ON topology_edges (topology_id, operation_id, child_node_id, parent_node_id);

CREATE TABLE IF NOT EXISTS topology_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topology_id BIGINT NOT NULL REFERENCES topology_models(id) ON DELETE CASCADE,
    operation_id BIGINT NOT NULL REFERENCES topology_discovery_operations(id) ON DELETE RESTRICT,
    version_number INTEGER NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    node_count INTEGER NOT NULL,
    edge_count INTEGER NOT NULL,
    summary_json TEXT,
    created_by VARCHAR(120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (topology_id, version_number)
);

CREATE INDEX IF NOT EXISTS idx_topology_versions_model
    ON topology_versions (topology_id, version_number DESC);
