-- Forge Scenario Fabric: governed business test domains, reusable scenario blueprints,
-- tester missions, generated coverage cases, and retained ready-to-test evidence.

CREATE TABLE scenario_domains (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topology_id BIGINT NOT NULL REFERENCES topology_models(id) ON DELETE RESTRICT,
    topology_version INTEGER NOT NULL,
    topology_hash VARCHAR(64) NOT NULL,
    name VARCHAR(120) NOT NULL,
    business_domain VARCHAR(120),
    description VARCHAR(2000),
    status VARCHAR(24) NOT NULL DEFAULT 'PUBLISHED',
    version_no INTEGER NOT NULL DEFAULT 1,
    settings_json TEXT NOT NULL DEFAULT '{}',
    owner_user_id BIGINT REFERENCES forge_users(id) ON DELETE SET NULL,
    owner_username VARCHAR(120),
    owner_group_id BIGINT REFERENCES forge_groups(id) ON DELETE SET NULL,
    visibility VARCHAR(16) NOT NULL DEFAULT 'GROUP',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_scenario_domains_topology ON scenario_domains(topology_id, topology_version);
CREATE INDEX idx_scenario_domains_tenancy ON scenario_domains(visibility, owner_group_id, owner_user_id);

CREATE TABLE scenario_domain_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id BIGINT NOT NULL REFERENCES scenario_domains(id) ON DELETE CASCADE,
    asset_type VARCHAR(40) NOT NULL,
    artifact_id VARCHAR(120) NOT NULL,
    artifact_version INTEGER,
    asset_role VARCHAR(40) NOT NULL DEFAULT 'EXECUTION',
    required BOOLEAN NOT NULL DEFAULT TRUE,
    config_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(domain_id, asset_type, artifact_id, asset_role)
);

CREATE INDEX idx_scenario_domain_assets ON scenario_domain_assets(domain_id, asset_type);

CREATE TABLE scenario_blueprints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id BIGINT NOT NULL REFERENCES scenario_domains(id) ON DELETE CASCADE,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(2000),
    entity_type VARCHAR(120) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PUBLISHED',
    version_no INTEGER NOT NULL DEFAULT 1,
    preconditions_json TEXT NOT NULL DEFAULT '[]',
    event_json TEXT NOT NULL DEFAULT '{}',
    expected_json TEXT NOT NULL DEFAULT '[]',
    coverage_json TEXT NOT NULL DEFAULT '{}',
    delivery_json TEXT NOT NULL DEFAULT '{}',
    questionnaire_json TEXT NOT NULL DEFAULT '[]',
    verification_json TEXT NOT NULL DEFAULT '{}',
    owner_user_id BIGINT REFERENCES forge_users(id) ON DELETE SET NULL,
    owner_username VARCHAR(120),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_scenario_blueprints_domain ON scenario_blueprints(domain_id, status, updated_at);

CREATE TABLE scenario_blueprint_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blueprint_id BIGINT NOT NULL REFERENCES scenario_blueprints(id) ON DELETE CASCADE,
    domain_id BIGINT NOT NULL REFERENCES scenario_domains(id) ON DELETE CASCADE,
    version_no INTEGER NOT NULL,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(2000),
    entity_type VARCHAR(120) NOT NULL,
    status VARCHAR(24) NOT NULL,
    preconditions_json TEXT NOT NULL,
    event_json TEXT NOT NULL,
    expected_json TEXT NOT NULL,
    coverage_json TEXT NOT NULL,
    delivery_json TEXT NOT NULL,
    questionnaire_json TEXT NOT NULL,
    verification_json TEXT NOT NULL,
    created_by VARCHAR(120),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(blueprint_id, version_no)
);

CREATE INDEX idx_scenario_blueprint_versions
    ON scenario_blueprint_versions(blueprint_id, version_no DESC);

CREATE TABLE scenario_missions (
    id VARCHAR(36) PRIMARY KEY,
    domain_id BIGINT NOT NULL REFERENCES scenario_domains(id) ON DELETE RESTRICT,
    blueprint_id BIGINT NOT NULL REFERENCES scenario_blueprints(id) ON DELETE RESTRICT,
    blueprint_version INTEGER NOT NULL,
    title VARCHAR(160) NOT NULL,
    intent_text TEXT NOT NULL,
    target_environment VARCHAR(120),
    source_strategy VARCHAR(32) NOT NULL DEFAULT 'AUTO',
    requested_count BIGINT NOT NULL DEFAULT 1,
    parameters_json TEXT NOT NULL DEFAULT '{}',
    reservation_requested BOOLEAN NOT NULL DEFAULT FALSE,
    reservation_hours INTEGER,
    status VARCHAR(32) NOT NULL DEFAULT 'PLANNED',
    plan_json TEXT NOT NULL DEFAULT '{}',
    coverage_json TEXT NOT NULL DEFAULT '{}',
    verification_json TEXT NOT NULL DEFAULT '{}',
    ready_pack_json TEXT NOT NULL DEFAULT '{}',
    self_service_order_id VARCHAR(36) REFERENCES self_service_orders(id) ON DELETE SET NULL,
    requested_by_id BIGINT REFERENCES forge_users(id) ON DELETE SET NULL,
    requested_by VARCHAR(120) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    launched_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_scenario_missions_owner ON scenario_missions(requested_by_id, created_at DESC);
CREATE INDEX idx_scenario_missions_status ON scenario_missions(status, updated_at DESC);

CREATE TABLE scenario_mission_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mission_id VARCHAR(36) NOT NULL REFERENCES scenario_missions(id) ON DELETE CASCADE,
    ordinal_no INTEGER NOT NULL,
    case_key VARCHAR(120) NOT NULL,
    title VARCHAR(240) NOT NULL,
    case_kind VARCHAR(40) NOT NULL,
    inputs_json TEXT NOT NULL DEFAULT '{}',
    expected_json TEXT NOT NULL DEFAULT '{}',
    status VARCHAR(24) NOT NULL DEFAULT 'PLANNED',
    evidence_json TEXT NOT NULL DEFAULT '{}',
    UNIQUE(mission_id, ordinal_no),
    UNIQUE(mission_id, case_key)
);

CREATE INDEX idx_scenario_mission_cases ON scenario_mission_cases(mission_id, ordinal_no);

CREATE TABLE scenario_mission_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mission_id VARCHAR(36) NOT NULL REFERENCES scenario_missions(id) ON DELETE CASCADE,
    event_type VARCHAR(60) NOT NULL,
    actor VARCHAR(120) NOT NULL,
    message VARCHAR(2000),
    detail_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_scenario_mission_events ON scenario_mission_events(mission_id, created_at);
