-- Reusable, versioned synthetic design assets. Drafts remain editable; published
-- versions and compiled scenario manifests are immutable execution evidence.

CREATE TABLE synthetic_assets (
    id VARCHAR(36) PRIMARY KEY,
    asset_type VARCHAR(32) NOT NULL,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(2000),
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    draft_json TEXT NOT NULL DEFAULT '{}',
    current_version INTEGER NOT NULL DEFAULT 0,
    owner_user_id BIGINT REFERENCES forge_users(id) ON DELETE SET NULL,
    owner_username VARCHAR(120),
    owner_group_id BIGINT REFERENCES forge_groups(id) ON DELETE SET NULL,
    visibility VARCHAR(16) NOT NULL DEFAULT 'GROUP',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_synthetic_assets_type_status
    ON synthetic_assets(asset_type, status, updated_at);
CREATE INDEX idx_synthetic_assets_tenancy
    ON synthetic_assets(visibility, owner_group_id, owner_user_id);

CREATE TABLE synthetic_asset_versions (
    id VARCHAR(36) PRIMARY KEY,
    asset_id VARCHAR(36) NOT NULL REFERENCES synthetic_assets(id) ON DELETE CASCADE,
    version_no INTEGER NOT NULL,
    schema_version INTEGER NOT NULL DEFAULT 1,
    content_json TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    compatibility_level VARCHAR(24) NOT NULL DEFAULT 'COMPATIBLE',
    published_by VARCHAR(120),
    published_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(asset_id, version_no)
);

CREATE INDEX idx_synthetic_asset_versions
    ON synthetic_asset_versions(asset_id, version_no DESC);

CREATE TABLE synthetic_asset_dependencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_version_id VARCHAR(36) NOT NULL REFERENCES synthetic_asset_versions(id) ON DELETE CASCADE,
    dependency_asset_id VARCHAR(36) NOT NULL REFERENCES synthetic_assets(id) ON DELETE RESTRICT,
    dependency_version INTEGER NOT NULL,
    dependency_kind VARCHAR(40) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(owner_version_id, dependency_asset_id, dependency_version, dependency_kind)
);

CREATE INDEX idx_synthetic_asset_dependency_target
    ON synthetic_asset_dependencies(dependency_asset_id, dependency_version);

CREATE TABLE synthetic_scenario_manifests (
    id VARCHAR(36) PRIMARY KEY,
    scenario_asset_id VARCHAR(36) NOT NULL REFERENCES synthetic_assets(id) ON DELETE CASCADE,
    scenario_version INTEGER NOT NULL,
    scenario_version_id VARCHAR(36) NOT NULL REFERENCES synthetic_asset_versions(id) ON DELETE CASCADE,
    component_manifest_json TEXT NOT NULL,
    compiled_plan_json TEXT NOT NULL,
    component_hash VARCHAR(64) NOT NULL,
    plan_hash VARCHAR(64) NOT NULL,
    compiled_by VARCHAR(120),
    compiled_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_synthetic_scenario_manifests
    ON synthetic_scenario_manifests(scenario_asset_id, scenario_version, compiled_at DESC);

CREATE TABLE synthetic_plugin_registry (
    id VARCHAR(36) PRIMARY KEY,
    plugin_type VARCHAR(32) NOT NULL,
    plugin_key VARCHAR(120) NOT NULL,
    plugin_version VARCHAR(40) NOT NULL,
    descriptor_json TEXT NOT NULL DEFAULT '{}',
    implementation_class VARCHAR(500),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    certification_status VARCHAR(24) NOT NULL DEFAULT 'BUILT_IN',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(plugin_type, plugin_key, plugin_version)
);

