ALTER TABLE provision_jobs ADD COLUMN execution_metrics_json TEXT;

CREATE TABLE provision_job_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    table_name VARCHAR(512) NOT NULL,
    chunk_no INTEGER NOT NULL,
    state VARCHAR(30) NOT NULL,
    resume_key VARCHAR(2000),
    rows_read BIGINT DEFAULT 0 NOT NULL,
    rows_written BIGINT DEFAULT 0 NOT NULL,
    bytes_staged BIGINT DEFAULT 0 NOT NULL,
    loader_strategy VARCHAR(100),
    cursor_mode VARCHAR(100),
    attempts INTEGER DEFAULT 1 NOT NULL,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    error_message TEXT,
    table_complete BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT fk_provision_chunk_job FOREIGN KEY (job_id) REFERENCES provision_jobs(id) ON DELETE CASCADE,
    CONSTRAINT uq_provision_job_chunk UNIQUE (job_id, table_name, chunk_no)
);

CREATE INDEX idx_provision_chunk_job_state ON provision_job_chunks(job_id, state);
