-- Versioned, auditable schema-drift evidence for DataScope blueprints.
-- Snapshots are normalized JSON so one model works across PostgreSQL, Oracle, SQL Server,
-- DB2, MySQL and JDBC fallback connectors without coupling the control database to a vendor.
CREATE TABLE schema_drift_baselines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id BIGINT NOT NULL REFERENCES dataset_definitions(id) ON DELETE CASCADE,
    version_no INTEGER NOT NULL,
    fingerprint VARCHAR(64) NOT NULL,
    snapshot_json TEXT NOT NULL,
    acceptance_reason VARCHAR(1000) NOT NULL,
    accepted_by VARCHAR(120) NOT NULL,
    accepted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_schema_drift_baseline_version UNIQUE (dataset_id, version_no)
);

CREATE INDEX idx_schema_drift_baseline_active
    ON schema_drift_baselines(dataset_id, active, version_no);

CREATE TABLE schema_drift_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id BIGINT NOT NULL REFERENCES dataset_definitions(id) ON DELETE CASCADE,
    baseline_id BIGINT REFERENCES schema_drift_baselines(id) ON DELETE SET NULL,
    trigger_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    fingerprint VARCHAR(64),
    issue_count INTEGER NOT NULL DEFAULT 0,
    blocking_count INTEGER NOT NULL DEFAULT 0,
    summary_json TEXT NOT NULL,
    issues_json TEXT NOT NULL,
    snapshot_json TEXT NOT NULL,
    checked_by VARCHAR(120) NOT NULL,
    checked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_schema_drift_runs_dataset
    ON schema_drift_runs(dataset_id, checked_at);

CREATE TABLE schema_drift_schedules (
    dataset_id BIGINT PRIMARY KEY REFERENCES dataset_definitions(id) ON DELETE CASCADE,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    cron_expression VARCHAR(120),
    zone_id VARCHAR(80) NOT NULL DEFAULT 'UTC',
    next_run_at TIMESTAMP,
    last_run_at TIMESTAMP,
    configured_by VARCHAR(120) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_schema_drift_schedule_due
    ON schema_drift_schedules(enabled, next_run_at);
