'use client';

import { useMemo, useState } from 'react';
import { Badge, Button, Code, Group, Paper, ScrollArea, SimpleGrid, Stack, Table, Text, TextInput } from '@mantine/core';
import { IconDownload, IconPlayerPlay, IconSearch } from '@tabler/icons-react';
import type { Dialect } from '../transform-library';

export function FunctionLibrary({ dialect, groups, onInsert, onTest }: { dialect: Dialect; groups: Record<string, string[]>; onInsert: (value: string) => void; onTest: (value: string) => Promise<string> }) {
  const [search, setSearch] = useState(''); const [expression, setExpression] = useState(''); const [result, setResult] = useState(''); const [testing, setTesting] = useState(false);
  const filtered = useMemo(() => Object.entries(groups).map(([category, values]) => [category, values.filter((value) => !search || value.toLowerCase().includes(search.toLowerCase()))] as const).filter(([, values]) => values.length), [groups, search]);
  const test = async () => { if (!expression.trim()) return; setTesting(true); try { setResult(await onTest(expression.trim())); } catch (error) { setResult(error instanceof Error ? error.message : String(error)); } finally { setTesting(false); } };
  return <Paper className="mapx-panel" p="md"><Group justify="space-between" align="flex-start"><div><Group gap="xs"><Text fw={800}>Dialect-aware function library</Text><Badge variant="light">{dialect.toUpperCase()}</Badge></Group><Text size="sm" c="dimmed">Insert a function into the transformation pipeline or prove an expression against one live source row.</Text></div><TextInput leftSection={<IconSearch size={14} />} placeholder="Search functions" value={search} onChange={(event) => setSearch(event.currentTarget.value)} /></Group><SimpleGrid cols={{ base: 1, md: 2, xl: 3 }} mt="md">{filtered.map(([category, values]) => <div className="mapx-function-group" key={category}><Text size="xs" fw={800} c="dimmed" mb={6}>{category}</Text><Group gap={5}>{values.map((value) => <button type="button" className="mapx-function-chip" key={value} onClick={() => { setExpression(value); onInsert(value); }} title="Insert into the expression pipeline">{value}</button>)}</Group></div>)}</SimpleGrid><Group mt="md" align="flex-end"><TextInput label="Test expression on the live source" value={expression} onChange={(event) => setExpression(event.currentTarget.value)} placeholder="UPPER(first_name)" style={{ flex: 1 }} spellCheck={false} /><Button variant="default" leftSection={<IconPlayerPlay size={14} />} loading={testing} onClick={() => void test()}>Test</Button></Group>{result ? <Code block mt="sm">{result}</Code> : null}</Paper>;
}

export function SqlLineagePanel({ sql, lineage, onSqlChange }: { sql: string; lineage: Array<{ output: string; expression: string; sources: string[]; via: string }>; onSqlChange: (value: string) => void }) {
  const download = () => {
    const cell = (value: unknown) => `"${String(value ?? '').replaceAll('"', '""')}"`;
    const csv = ['output_column,expression,sourced_from,via', ...lineage.map((row) => [row.output, row.expression, row.sources.join(' | '), row.via].map(cell).join(','))].join('\r\n');
    const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); anchor.download = 'mapping-lineage.csv'; anchor.click(); URL.revokeObjectURL(anchor.href);
  };
  return <Stack gap="md"><Paper className="mapx-panel" p="md"><Group justify="space-between" mb="sm"><div><Text fw={800}>Generated source SQL</Text><Text size="sm" c="dimmed">Regenerate by changing the visual map or transformation pipeline. Advanced users may make a reviewed override here.</Text></div><Badge variant="light">Read-only source route</Badge></Group><textarea className="mapx-sql-editor" value={sql} onChange={(event) => onSqlChange(event.currentTarget.value)} spellCheck={false} /></Paper><Paper className="mapx-panel" p="md"><Group justify="space-between" mb="sm"><div><Text fw={800}>Column lineage</Text><Text size="sm" c="dimmed">Trace each output to source references and transformation evidence.</Text></div><Button size="xs" variant="default" leftSection={<IconDownload size={14} />} disabled={!lineage.length} onClick={download}>Export CSV</Button></Group><ScrollArea><Table striped withTableBorder className="mapx-lineage-table"><Table.Thead><Table.Tr><Table.Th>Output</Table.Th><Table.Th>Expression</Table.Th><Table.Th>Source references</Table.Th><Table.Th>Via</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{lineage.map((row, index) => <Table.Tr key={`${row.output}-${index}`}><Table.Td><Text fw={750}>{row.output}</Text></Table.Td><Table.Td><Code>{row.expression}</Code></Table.Td><Table.Td>{row.sources.length ? row.sources.map((source) => <Badge key={source} size="xs" variant="outline" mr={4}>{source}</Badge>) : <Text size="xs" c="dimmed">Generated or literal</Text>}</Table.Td><Table.Td>{row.via}</Table.Td></Table.Tr>)}{!lineage.length ? <Table.Tr><Table.Td colSpan={4}><Text c="dimmed" ta="center" py="lg">Map columns or add expression stages to calculate lineage.</Text></Table.Td></Table.Tr> : null}</Table.Tbody></Table></ScrollArea></Paper></Stack>;
}
