'use client';

import { ActionIcon, Badge, Button, Group, NumberInput, Paper, Select, SimpleGrid, Stack, Switch, Text, TextInput, Tooltip } from '@mantine/core';
import { IconArrowDown, IconArrowUp, IconPlus, IconTrash } from '@tabler/icons-react';
import type { MappingTransform } from '../types';
import { newTransform, TRANSFORM_CATALOG, transformName } from '../transform-library';

export function TransformationStudio({ transforms, onChange }: { transforms: MappingTransform[]; onChange: (transforms: MappingTransform[]) => void }) {
  const add = (type: string | null) => { if (type) onChange([...transforms, newTransform(type)]); };
  const patch = (index: number, update: Partial<MappingTransform>) => onChange(transforms.map((item, position) => position === index ? { ...item, ...update, requiresConfiguration: false } : item));
  const move = (index: number, direction: number) => { const target = index + direction; if (target < 0 || target >= transforms.length) return; const next = [...transforms]; [next[index], next[target]] = [next[target], next[index]]; onChange(next); };
  return <Paper className="mapx-panel" p="md"><Group justify="space-between" align="flex-start"><div><Group gap="xs"><Text fw={800}>Transformation pipeline</Text><Badge variant="light">{transforms.length} stages</Badge></Group><Text size="sm" c="dimmed">Stages compile in order into source-dialect SQL and remain visible as nodes on the visual map.</Text></div><Select placeholder="Add transformation" data={TRANSFORM_CATALOG.map(([value, label, description]) => ({ value, label, description }))} leftSection={<IconPlus size={15} />} onChange={add} value={null} searchable w={230} /></Group><Stack gap="sm" mt="md">{transforms.map((transform, index) => <Paper key={String(transform.id || index)} className="mapx-transform-card" p="sm" withBorder><Group justify="space-between" mb="sm"><div><Group gap="xs"><Badge>{index + 1}</Badge><Text fw={800}>{transformName(transform.type)}</Text></Group><Text size="xs" c="dimmed">{TRANSFORM_CATALOG.find((item) => item[0] === transform.type)?.[2]}</Text></div><Group gap={4}><Tooltip label="Move up"><ActionIcon variant="subtle" disabled={index === 0} onClick={() => move(index, -1)}><IconArrowUp size={15} /></ActionIcon></Tooltip><Tooltip label="Move down"><ActionIcon variant="subtle" disabled={index === transforms.length - 1} onClick={() => move(index, 1)}><IconArrowDown size={15} /></ActionIcon></Tooltip><Tooltip label="Remove stage"><ActionIcon color="red" variant="subtle" onClick={() => onChange(transforms.filter((_, position) => position !== index))}><IconTrash size={15} /></ActionIcon></Tooltip></Group></Group><TransformFields transform={transform} patch={(update) => patch(index, update)} /></Paper>)}{!transforms.length ? <Text c="dimmed" ta="center" py="xl">No transformations yet. Source rows pass directly to the column map.</Text> : null}</Stack></Paper>;
}

function TransformFields({ transform, patch }: { transform: MappingTransform; patch: (update: Partial<MappingTransform>) => void }) {
  if (transform.type === 'FILTER') return <TextInput label="Filter condition" value={text(transform.condition)} onChange={(event) => patch({ condition: event.currentTarget.value })} placeholder="status = 'ACTIVE' AND region = 'US'" spellCheck={false} />;
  if (transform.type === 'EXPRESSION') {
    const columns = records(transform.columns);
    return <Stack gap="xs">{columns.map((column, index) => <Group key={index} wrap="nowrap"><TextInput aria-label="Output column" value={text(column.name)} placeholder="output_column" onChange={(event) => patch({ columns: updateRecord(columns, index, { name: event.currentTarget.value }) })} w={220} spellCheck={false} /><Text>=</Text><TextInput aria-label="Expression" value={text(column.expr)} placeholder="UPPER(source.first_name)" onChange={(event) => patch({ columns: updateRecord(columns, index, { expr: event.currentTarget.value }) })} style={{ flex: 1 }} spellCheck={false} /><ActionIcon color="red" variant="subtle" onClick={() => patch({ columns: columns.filter((_, position) => position !== index) })}><IconTrash size={14} /></ActionIcon></Group>)}<Button size="xs" variant="subtle" leftSection={<IconPlus size={14} />} onClick={() => patch({ columns: [...columns, { name: '', expr: '' }] })}>Add expression</Button></Stack>;
  }
  if (transform.type === 'AGGREGATOR') {
    const aggregates = records(transform.aggregates);
    return <Stack gap="xs"><TextInput label="Group by columns" value={listText(transform.groupBy)} onChange={(event) => patch({ groupBy: comma(event.currentTarget.value) })} placeholder="region, account_type" spellCheck={false} />{aggregates.map((aggregate, index) => <Group key={index} wrap="nowrap"><TextInput value={text(aggregate.name)} placeholder="total_balance" onChange={(event) => patch({ aggregates: updateRecord(aggregates, index, { name: event.currentTarget.value }) })} w={220} spellCheck={false} /><Text>=</Text><TextInput value={text(aggregate.expr)} placeholder="SUM(balance)" onChange={(event) => patch({ aggregates: updateRecord(aggregates, index, { expr: event.currentTarget.value }) })} style={{ flex: 1 }} spellCheck={false} /><ActionIcon color="red" variant="subtle" onClick={() => patch({ aggregates: aggregates.filter((_, position) => position !== index) })}><IconTrash size={14} /></ActionIcon></Group>)}<Button size="xs" variant="subtle" leftSection={<IconPlus size={14} />} onClick={() => patch({ aggregates: [...aggregates, { name: '', expr: '' }] })}>Add aggregate</Button></Stack>;
  }
  if (transform.type === 'SORTER') {
    const sort = records(transform.sort);
    return <Stack gap="xs">{sort.map((item, index) => <Group key={index} wrap="nowrap"><TextInput value={text(item.col)} placeholder="created_on" onChange={(event) => patch({ sort: updateRecord(sort, index, { col: event.currentTarget.value }) })} style={{ flex: 1 }} spellCheck={false} /><Select data={['ASC', 'DESC']} value={text(item.dir) || 'ASC'} onChange={(value) => patch({ sort: updateRecord(sort, index, { dir: value || 'ASC' }) })} w={110} /><ActionIcon color="red" variant="subtle" onClick={() => patch({ sort: sort.filter((_, position) => position !== index) })}><IconTrash size={14} /></ActionIcon></Group>)}<Button size="xs" variant="subtle" leftSection={<IconPlus size={14} />} onClick={() => patch({ sort: [...sort, { col: '', dir: 'ASC' }] })}>Add sort key</Button></Stack>;
  }
  if (transform.type === 'DISTINCT') return <Text size="sm" c="dimmed">Duplicate result rows are removed with SELECT DISTINCT.</Text>;
  if (transform.type === 'LIMIT') return <NumberInput label="Maximum rows" min={1} allowDecimal={false} value={numberOrBlank(transform.rows)} onChange={(value) => patch({ rows: value })} />;
  if (transform.type === 'ROUTER') {
    const groups = records(transform.groups);
    return <Stack gap="xs"><Select label="Active route for preview" data={groups.map((group, index) => ({ value: String(index), label: text(group.name) || `Route ${index + 1}` }))} value={String(transform.active || 0)} onChange={(value) => patch({ active: Number(value || 0) })} />{groups.map((group, index) => <SimpleGrid key={index} cols={{ base: 1, md: 4 }}><TextInput label="Route name" value={text(group.name)} onChange={(event) => patch({ groups: updateRecord(groups, index, { name: event.currentTarget.value }) })} /><TextInput label="Condition" value={text(group.condition)} onChange={(event) => patch({ groups: updateRecord(groups, index, { condition: event.currentTarget.value }) })} spellCheck={false} /><TextInput label="Target schema" value={text(group.targetSchema)} onChange={(event) => patch({ groups: updateRecord(groups, index, { targetSchema: event.currentTarget.value }) })} spellCheck={false} /><Group align="flex-end" wrap="nowrap"><TextInput label="Target table" value={text(group.target)} onChange={(event) => patch({ groups: updateRecord(groups, index, { target: event.currentTarget.value }) })} spellCheck={false} /><ActionIcon color="red" variant="subtle" mb={4} onClick={() => patch({ groups: groups.filter((_, position) => position !== index) })}><IconTrash size={14} /></ActionIcon></Group></SimpleGrid>)}<Button size="xs" variant="subtle" leftSection={<IconPlus size={14} />} onClick={() => patch({ groups: [...groups, { name: `Route ${groups.length + 1}`, condition: '', targetSchema: '', target: '' }] })}>Add route</Button></Stack>;
  }
  if (transform.type === 'UNION') return <Stack gap="xs"><SimpleGrid cols={{ base: 1, md: 3 }}><TextInput label="Schema" value={text(transform.schema)} onChange={(event) => patch({ schema: event.currentTarget.value })} spellCheck={false} /><TextInput label="Table" value={text(transform.table)} onChange={(event) => patch({ table: event.currentTarget.value })} spellCheck={false} /><TextInput label="Projected columns" value={text(transform.columns)} onChange={(event) => patch({ columns: event.currentTarget.value })} placeholder="*" spellCheck={false} /></SimpleGrid><TextInput label="Optional union filter" value={text(transform.condition)} onChange={(event) => patch({ condition: event.currentTarget.value })} spellCheck={false} /><Switch label="UNION ALL (keep duplicates)" checked={transform.all !== false} onChange={(event) => patch({ all: event.currentTarget.checked })} /></Stack>;
  if (transform.type === 'LOOKUP') return <Stack gap="xs"><SimpleGrid cols={{ base: 1, md: 3 }}><TextInput label="Schema" value={text(transform.schema)} onChange={(event) => patch({ schema: event.currentTarget.value })} spellCheck={false} /><TextInput label="Lookup table" value={text(transform.table)} onChange={(event) => patch({ table: event.currentTarget.value })} spellCheck={false} /><TextInput label="Alias" value={text(transform.alias)} onChange={(event) => patch({ alias: event.currentTarget.value })} placeholder="lk1" spellCheck={false} /></SimpleGrid><TextInput label="Match condition" value={text(transform.on)} onChange={(event) => patch({ on: event.currentTarget.value })} placeholder="source.rating_code = lk1.code" spellCheck={false} /><TextInput label="Return columns" value={text(transform.returns)} onChange={(event) => patch({ returns: event.currentTarget.value })} placeholder="lk1.rating AS credit_rating" spellCheck={false} /></Stack>;
  if (transform.type === 'RANK') return <SimpleGrid cols={{ base: 1, md: 4 }}><TextInput label="Partition by" value={text(transform.partitionBy)} onChange={(event) => patch({ partitionBy: event.currentTarget.value })} spellCheck={false} /><TextInput label="Order by" value={text(transform.orderBy)} onChange={(event) => patch({ orderBy: event.currentTarget.value })} required spellCheck={false} /><NumberInput label="Top N" min={1} value={numberOrBlank(transform.topN)} onChange={(value) => patch({ topN: value })} /><TextInput label="Rank column" value={text(transform.name)} onChange={(event) => patch({ name: event.currentTarget.value })} placeholder="rank_in_group" spellCheck={false} /></SimpleGrid>;
  if (transform.type === 'SEQUENCE') return <SimpleGrid cols={{ base: 1, md: 2 }}><TextInput label="Sequence column" value={text(transform.name)} onChange={(event) => patch({ name: event.currentTarget.value })} placeholder="seq_no" spellCheck={false} /><TextInput label="Order by" value={text(transform.orderBy)} onChange={(event) => patch({ orderBy: event.currentTarget.value })} placeholder="id" spellCheck={false} /></SimpleGrid>;
  if (transform.type === 'PIVOT') return <Stack gap="xs"><SimpleGrid cols={{ base: 1, md: 3 }}><TextInput label="Group by" value={listText(transform.groupBy)} onChange={(event) => patch({ groupBy: event.currentTarget.value })} spellCheck={false} /><TextInput label="Category column" value={text(transform.category)} onChange={(event) => patch({ category: event.currentTarget.value })} spellCheck={false} /><TextInput label="Value column" value={text(transform.value)} onChange={(event) => patch({ value: event.currentTarget.value })} spellCheck={false} /></SimpleGrid><SimpleGrid cols={{ base: 1, md: 2 }}><TextInput label="Pivot values" value={text(transform.values)} onChange={(event) => patch({ values: event.currentTarget.value })} placeholder="A1, A2, A3" /><Select label="Aggregate" data={['SUM', 'COUNT', 'AVG', 'MIN', 'MAX']} value={text(transform.agg) || 'SUM'} onChange={(value) => patch({ agg: value || 'SUM' })} /></SimpleGrid></Stack>;
  return <Text size="sm" c="dimmed">This preserved transformation can be viewed in generated SQL and lineage.</Text>;
}

function records(value: unknown): Array<Record<string, unknown>> { return Array.isArray(value) ? value as Array<Record<string, unknown>> : []; }
function updateRecord(rows: Array<Record<string, unknown>>, index: number, patch: Record<string, unknown>) { return rows.map((row, position) => position === index ? { ...row, ...patch } : row); }
function text(value: unknown) { return value == null ? '' : String(value); }
function comma(value: string) { return value.split(',').map((item) => item.trim()).filter(Boolean); }
function listText(value: unknown) { return Array.isArray(value) ? value.join(', ') : text(value); }
function numberOrBlank(value: unknown): number | '' { const number = Number(value || 0); return number > 0 ? number : ''; }
