-- ForgeTDM Business Entity demo for Oracle 12c+
-- Root business entity: FTDM_BE_CUSTOMER
-- Business key: CUSTOMER_NO
-- Child relationship: FTDM_BE_ACCOUNT.CUSTOMER_ID -> FTDM_BE_CUSTOMER.CUSTOMER_ID

CREATE TABLE FTDM_BE_CUSTOMER (
    CUSTOMER_ID       NUMBER(19)       NOT NULL,
    CUSTOMER_NO       VARCHAR2(30 CHAR) NOT NULL,
    FIRST_NAME        VARCHAR2(80 CHAR) NOT NULL,
    LAST_NAME         VARCHAR2(80 CHAR) NOT NULL,
    EMAIL_ADDRESS     VARCHAR2(254 CHAR),
    PHONE_NUMBER      VARCHAR2(30 CHAR),
    DATE_OF_BIRTH     DATE,
    TAX_IDENTIFIER    VARCHAR2(20 CHAR),
    CUSTOMER_STATUS   VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_FTDM_BE_CUSTOMER PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT UK_FTDM_BE_CUSTOMER_NO UNIQUE (CUSTOMER_NO),
    CONSTRAINT CK_FTDM_BE_CUST_STATUS
        CHECK (CUSTOMER_STATUS IN ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'CLOSED'))
);

CREATE TABLE FTDM_BE_ACCOUNT (
    ACCOUNT_ID        NUMBER(19)        NOT NULL,
    ACCOUNT_NO        VARCHAR2(34 CHAR) NOT NULL,
    CUSTOMER_ID       NUMBER(19)        NOT NULL,
    ACCOUNT_TYPE      VARCHAR2(20 CHAR) NOT NULL,
    ACCOUNT_STATUS    VARCHAR2(20 CHAR) DEFAULT 'OPEN' NOT NULL,
    CURRENCY_CODE     CHAR(3 CHAR) DEFAULT 'USD' NOT NULL,
    CURRENT_BALANCE   NUMBER(18,2) DEFAULT 0 NOT NULL,
    OPENED_ON         DATE DEFAULT SYSDATE NOT NULL,
    CLOSED_ON         DATE,
    CREATED_AT        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_FTDM_BE_ACCOUNT PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT UK_FTDM_BE_ACCOUNT_NO UNIQUE (ACCOUNT_NO),
    CONSTRAINT FK_FTDM_BE_ACCT_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES FTDM_BE_CUSTOMER (CUSTOMER_ID),
    CONSTRAINT CK_FTDM_BE_ACCT_TYPE
        CHECK (ACCOUNT_TYPE IN ('CHECKING', 'SAVINGS', 'CREDIT_CARD', 'LOAN')),
    CONSTRAINT CK_FTDM_BE_ACCT_STATUS
        CHECK (ACCOUNT_STATUS IN ('OPEN', 'DORMANT', 'FROZEN', 'CLOSED')),
    CONSTRAINT CK_FTDM_BE_ACCT_DATES
        CHECK (CLOSED_ON IS NULL OR CLOSED_ON >= OPENED_ON)
);

CREATE INDEX IX_FTDM_BE_ACCOUNT_CUSTOMER
    ON FTDM_BE_ACCOUNT (CUSTOMER_ID);

CREATE INDEX IX_FTDM_BE_CUSTOMER_UPDATED
    ON FTDM_BE_CUSTOMER (UPDATED_AT);

CREATE INDEX IX_FTDM_BE_ACCOUNT_UPDATED
    ON FTDM_BE_ACCOUNT (UPDATED_AT);

COMMENT ON TABLE FTDM_BE_CUSTOMER IS
    'ForgeTDM demo Business Entity root table';

COMMENT ON COLUMN FTDM_BE_CUSTOMER.CUSTOMER_NO IS
    'Stable cross-application business key used to identify one customer entity';

COMMENT ON TABLE FTDM_BE_ACCOUNT IS
    'ForgeTDM demo Business Entity child account table';

COMMENT ON COLUMN FTDM_BE_ACCOUNT.CUSTOMER_ID IS
    'Relationship to the owning customer entity';
